### ISSUE TITLE
How would I retrieve a collection of objects

### ISSUE THREAD

**Issue by jaybowman** [step-up-labs/firebase-database-dotnet#10]
I have a test project and I want to retrieve a list of items on a firebaseUser. I have this working on my Cordova hybred mobile app using angularfire. How would I do the same thing with you database package?
Javascript: 
 var root = firebase.database().ref();
// uid is the authenticated user's uid
  locations = $firebaseArray(root.child('users').child(uid).child('locations'));

C#:
 var config = new FirebaseConfig("my application key");
 var authProvider = new FirebaseAuthProvider(config);
 var auth = await authProvider.SignInWithEmailAndPasswordAsync("myemail@company.com", "password");
        
 var firebase = new FirebaseClient("https://myapp-at.firebaseio.com");
  var locations = firebase.Child("users").??? 

I don't see any of the linq methods with intellisense, am I missing some using statements.

Jay

**Comment by bezysoftware** [comment]
The method are in namespace `Firebase.Database.Query` so just add that to usings

**Comment by jaybowman** [comment]
Thanks, Your project looks very interesting. I'm still trying to just get a list from an auth user.
I get a 401 unauthorized when i leave the WithAuth() off, and I get a 400 bad request with the following statement.
  var locations = await firebase
                            .Child("users")
                            .Child(auth.User.LocalId)
                            .Child("locations")
                            .WithAuth(auth.User.LocalId)
                            .OnceAsync<Location>();

Attached is my firebase db structure.
![firebasedbstruct](https://cloud.githubusercontent.com/assets/4990535/18591221/be5851d4-7bff-11e6-8b53-c854aa48ab5c.PNG)

Any help would be greatly appreciated.

**Comment by bezysoftware** [comment]
You need to use `  .WithAuth(auth.FirebaseToken)` for authenticating

**Comment by jaybowman** [comment]
Thanks, that works.
