### ISSUE TITLE
HttpClient Timeout on Stream causing Subscribe to Retry

### ISSUE THREAD

**Issue by gorillapower** [step-up-labs/firebase-database-dotnet#100]
I have setup this observable (commented out filters because they would fail when data structure would change on firebase. See issue )

This code runs fine, however it seems the subscribe will keep firing after ~1:40mins and the only way to get around this is to filter on already 'processed' objects by way of a 'processed' field on the object.

```
var lastUpdate
  var fbBookings = fbHelper.Client.Child("bookings").OrderBy("updatedAtTS").StartAt((long)lastUpdate);
                    var observable = (from b in fbBookings.AsObservable<BookingsFireBaseModelUpdate>()
                                          //where b.Object != null && !string.IsNullOrEmpty(b.Object.attendanceCountUpdate)
                                          //|| !string.IsNullOrEmpty(b.Object.commentUpdate)
                                          //|| !string.IsNullOrEmpty(b.Object.waiverFormUpdate)
                                      select b).RetryWithBackoffStrategy(10);

                    var subs = observable
                   .Subscribe(async (x) =>
                   {
                      //processing
                   });
```
After doing some digging, I found that I repeatedly receive ` A task was canceled` exception after ~1:40mins. Which then restarts the stream connection to firebase and hence the behaviour observed above occurs.

```   
at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Http.DelegatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at Firebase.Database.Streaming.FirebaseSubscription`1.<ReceiveThread>d__14.MoveNext() in C:\dev\Tutorials\firebase-database-dotnet-master\src\Firebase\Streaming\FirebaseSubscription.cs:line 111
```
Seems to throw at this line `line = reader.ReadLine()?.Trim();` Ive checked, it doesnt seem to be counting against the connections in firebase...which is weird at first glance.

After more investigation it seems to be related to the default timeout on the httpclient doing the initial stream listening itself. See timeout docs on httpclient here https://msdn.microsoft.com/en-us/library/system.net.http.httpclient.timeout(v=vs.110).aspx

After adding the timeout  in the FirbaseSubscription.cs to `httpClient.Timeout = Timeout.InfiniteTimeSpan;` the exceptions stopped occuring.

Has anyone else experienced this behaviour? It seems to only happen in the Azure WebJob im running this in (continuous, NoAutomaticTrigger). Possibly a threading issue? I have no problems with the same code in a console app...

**Comment by IsaackRasmussen** [comment]
This sound very similar to the issue I'm seeing. #94 
But I'm not using Azure WebJobs just normal Windows Services.

Googling the timeout property, I see other devs saying its needed for streaming or it will timeout despite  heartbeats.
Interesting...  I'll try this myself

**Comment by SongYoungae** [comment]
Try .NET Framework 4.6.1 or later.

**Comment by guiltm** [comment]
> Isso soa muito semelhante ao problema que estou vendo. [# 94](https://github.com/step-up-labs/firebase-database-dotnet/issues/94)
> Mas não estou usando os WebJobs do Azure, apenas os serviços normais do Windows.
> 
> Pesquisando na propriedade timeout, vejo outros desenvolvedores dizendo que é necessário para streaming ou o tempo limite excede os batimentos cardíacos.
> Interessante ... vou tentar isso sozinho



> This sound very similar to the issue I'm seeing. #94
> But I'm not using Azure WebJobs just normal Windows Services.
> 
> Googling the timeout property, I see other devs saying its needed for streaming or it will timeout despite heartbeats.
> Interesting... I'll try this myself

Any new?
