### ISSUE TITLE
Not enough documentations 

### ISSUE THREAD

**Issue by dovahkiin98** [step-up-labs/firebase-database-dotnet#102]
Iin the example you used "OnceAsync" as a variable which returns a Task object in the foreach loop, and it tells me "the await operator can only be used within an async method"

**Comment by bezysoftware** [comment]
The method where you use `await` needs to be `async`, just like the one in the samples. See docs about async/await: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/await
