### ISSUE TITLE
Second subscription does not work

### ISSUE THREAD

**Issue by jhumphrey1** [step-up-labs/firebase-database-dotnet#103]
Creating a second subscription while one already exists does not work, or works very slowly.

Trying to create:

`firebase.Child("key").AsObservable<MyObject>().Subscribe(obj => { Debug.WriteLine("Object Received : " + JsonConvert.SerializeObject(onj)); ConsumeObject(obj); });`

note that calling a OnceSingleAsync call at the same location yields the correct result.
I even tried calling dispose on the reference to the previous subscription with no results

**Comment by bezysoftware** [comment]
You should optimally be reusing single observable and subscribe to it multiple times
