### ISSUE TITLE
query and post data so slow

### ISSUE THREAD

**Issue by passa1248** [step-up-labs/firebase-database-dotnet#106]
Hi all!
Is it normal that time for query and post data is it approximately 600 ms?
I need to query and post data about 700 every 5 minutes so now work with multithread but cpu percentage is very very hight..
Thanks in advance!

**Comment by toffuser** [comment]
I have the same issue here. I ask a Query and then it takes almost 10-15 seconds before I get the item I want.
                foreach (var cat in categorie)
                {
                items = await firebase
               .Child("Aliment")
               .Child("epicerie")
               .OnceAsync<Items>();

                    foreach (var item in items) .......

I'm pretty sure I ask to much for Firebase. Am I ?

**Comment by bezysoftware** [comment]
You can try doing the HTTP request manually yourself with HttpClient and see an issue with firebase or with this lib.

**Comment by GOPIKRISHNAN-1992** [comment]
Hi All, 

I am trying to use the below query to retrieve data from firebase. I just replaced the firebaseclient and child name as per my firebase realtime db.

Sample code :
`var firebase = new FirebaseClient(“https://dinosaur-facts.firebaseio.com/");
var dinos = await firebase
   .Child(“dinosaurs”)
   .OrderByKey()
   .StartAt(“pterodactyl”)
   .LimitToFirst(2)
   .OnceAsync<Dinosaur>();`

Ref : https://medium.com/step-up-labs/firebase-c-library-5c342989ad18

But the await request loading forever in a separate thread and doesn't return any response. When I tried using REST API (HttpClient) for firebase CRUD operation. It's working fine. But firebasedatabasedotnet DLL, await thread loading forever.

Am I missing anything here?

**Comment by webwarrior06** [comment]
Did you wrap your statement with try catch? Maybe you have unhandled exception. It may stem from type incompatibility used in OnceAsync generic method.

**Comment by GOPIKRISHNAN-1992** [comment]
Thank you @webwarrior06 . type incompatibility was the issue.

**Comment by Fabricciotcortes** [comment]
Hi it´s true Http Request is fater than FirebaseDataBase, in my case this packeges take 4 second to Put, Update, or Delete a elemento from my database. BTW: I use FirebaseDataBase because in HttpRequest i dont know how to get my data in real time. FirebaseDatabase have a method Subscribe() but its doesnt work if a i want to add their objects in a List().
