### ISSUE TITLE
Cloud Firecore?

### ISSUE THREAD

**Issue by Redth** [step-up-labs/firebase-database-dotnet#109]
Hey this library looks great!  Any plans to do something similar for Cloud Firecore? I know it was just announced, but seems like the same treatment for it would be really useful.

**Comment by SilverMountainSoftware** [comment]
Me too! This is also an opportunity to create migration scripts from Firebase to Firestore using your tools.

**Comment by pauloevpr** [comment]
I am also interested in Firestore support.

**Comment by khalid-halo** [comment]
Also interested in Firestore support

**Comment by Thaina** [comment]
Firestore too

**Comment by VicSmith** [comment]
Very Interested in Firestore as well.

**Comment by bezysoftware** [comment]
Sorry folks, I don't have any immediate plans for Firestore support. Maybe Google will come up with their official c# lib? (*sarcastic laugh*)

**Comment by Thaina** [comment]
@bezysoftware Actually it has. But only support server and PC though

https://www.nuget.org/packages/Google.Cloud.Firestore/1.0.0-beta01

**Comment by ShiroYacha** [comment]
@bezysoftware yeah and it does not support real-time updates...

**Comment by DiegoVenancioVieira** [comment]
none updates here?

**Comment by angelru** [comment]
Very Interested in Firestore as well.

**Comment by Brouilles** [comment]
Very Interested in Firestore as well.
