### ISSUE TITLE
Double "Put" when Streaming

### ISSUE THREAD

**Issue by alewcock** [step-up-labs/firebase-database-dotnet#11]
When new data is "pushed" to firebase, there appears to be a double "put" received when using the streaming api, after inspecting the result at FirebaseSubscription.cs:170

`var result = JObject.Parse(serverData);`

The first "put" contains only the new data:

`{"path":"/list/-KS-k0EWj76Oc3gtnVx0","data":{"name":"New Item 00:41:54 GMT-0400 (EDT)"}}`

The second "put" contains the entire data set:

`{"path":"/","data":{"list":{"-KS-esW1NFCmzLO_gu-_":{"name":"Old Item 00:19:25 GMT-0400 (EDT)"},"-KS-k0EWj76Oc3gtnVx0":{"name":"New Item 00:41:54 GMT-0400 (EDT)"}}}}`

Is this normal? Is the firebase REST API sending these back?

Thanks.

**Comment by bezysoftware** [comment]
I will check, if that is indeed the case it must be something new, because I don't remember it happening previously

**Comment by bezysoftware** [comment]
I just checked and it doesn't seem that server is sending the data twice (change + full). It is possible there is an exception within the subscription, in which case everything gets restarted - which results in the full fetch of data you are observing. 

The exceptions within subscription are swallowed at the moment, the only way for you to see them is to have a debugger attached in VS and look at the "output" window. I do realize this is rather unfortunate solution, I will add ExceptionThrown event so you can react to thrown exceptions.
