### ISSUE TITLE
Add "print=silent" parameter

### ISSUE THREAD

**Issue by luccasclezar** [step-up-labs/firebase-database-dotnet#111]
Right now there's no use for the returned data when patching the database. With the "print=silent" parameter there would be a reasonable bandwidth saving and it should be easy to implement as a Firebase Option (or hardcoded in all operations except GET).

I would make a PR if I knew exactly what to change, but I'm afraid I don't quite understand the code to do it myself.

**Comment by bezysoftware** [comment]
Great idea, I'll have a look at it next week when I return from vacation
