### ISSUE TITLE
PostAsync(T object)

### ISSUE THREAD

**Issue by bolorundurowb** [step-up-labs/firebase-database-dotnet#113]
I followed the tutorials and noticed that in the latest version of this library (3.0.3) on Nuget, `PostAsync` only allows for a string payload, what is the workaround for this, do we have to convert the strongly typed object to a string first or is this is a mistake?

**Comment by bezysoftware** [comment]
No it certainly allows a generic T payload, maybe missing using statement?

**Comment by devgeek27** [comment]
I've got the same issue. It actually string. PostAsync implementation looks like as follows:
`[AsyncStateMachine(typeof(<PostAsync>d__10))]
  public Task<FirebaseObject<string>> PostAsync(string data, bool generateKeyOffline = true);`

**Comment by bezysoftware** [comment]
"No it certainly allows a generic T payload, maybe missing using statement?"

https://github.com/step-up-labs/firebase-database-dotnet/blob/b1aed14653dd138d5c26251f6b8c16964b6a9909/src/Firebase/Query/QueryExtensions.cs#L164

**Comment by devgeek27** [comment]
I see. Thanks. This code needs to be included to make that work:
`using Firebase.Database.Query;`

**Comment by bolorundurowb** [comment]
@devgeek27 's solution worked for me. I think it should be added to the documentation and examples on medium so others don't find themselves in the same position.

**Comment by bezysoftware** [comment]
I planned to move it to the Firebase.Database namespace, but there is just never enough time... Also its a breaking change so increase the major version

**Comment by codegrue** [comment]
Where would I find the mentioned tutorials?

**Comment by bezysoftware** [comment]
Some samples can be found here: https://medium.com/step-up-labs/firebase-c-library-5c342989ad18

**Comment by codegrue** [comment]
The samples show queries well but nothing on doing an update. Something like a CRUD ToDo demo would be very helpful
________________________________
