### ISSUE TITLE
Update or set value for specific property?

### ISSUE THREAD

**Issue by mikeaveli007** [step-up-labs/firebase-database-dotnet#115]
Is there a way to Set or update a value for a specific property?  PostAsync() generates a new key\object and PutAsync() says it will overwrite any data that is already there.

**Comment by mikeaveli007** [comment]
Nevermind, I found the PatchAsync method which did exactly what I needed.

**Comment by lucazin** [comment]
Hey mike.. how u are using  PatchAsync to update?

im usng like this

   String xx = "dddd";
                await firebaseClient
               .Child("ESTABID_17")
               .Child("PEDIDOS_DELIVERY")
               .Child("-Lzhy-dZ9iFiJ823q9sMQ")
               .Child("codigoPedido")
               .PatchAsync(xx);

But i have a error..
