### ISSUE TITLE
Maintain Character Case for Keys

### ISSUE THREAD

**Issue by cabauman** [step-up-labs/firebase-database-dotnet#116]
Would it be simple to maintain the character case of database keys? For example, currently, it reads an object of the form:

User1
-name
-age

and then when I patch, my database looks like:

User1
-Name
-Age
-name
-age

or put:

User1
-Name
-Age

Is it based on the case of the property?

I wouldn't mind using "put" to override everything to use pascal case BUT it would be a breaking change for the Java implementation of my project on the market.

**Comment by cabauman** [comment]
I confirmed it's based on the case of the property so, as a temporary solution, I'm changing my properties to match those in the database.

**Comment by ytrikoz** [comment]
[JsonProperty(PropertyName = "**name**"), FireFanout("org_name")]
public string **Name** { get; set; }

**Comment by cabauman** [comment]
Thanks @ytrikoz. Figured it would be a simple solution. I should have Google searched json.net more before posting this issue. The following worked for me:

[JsonProperty("name")]
public string Name { get; set; }

"FireFanout" didn't yield any search results, so I have no idea what that is.
