### ISSUE TITLE
Xamarin sample

### ISSUE THREAD

**Issue by codegrue** [step-up-labs/firebase-database-dotnet#119]
Does anyone have a working Xamarin sample of Streaming and Offline in Xamarin? I got these to work with the console samples, but cannot seem to get reliable behavior in Xamarin.

**Comment by AndreasSchmid1** [comment]
would be interested in this as well

**Comment by nt2vna** [comment]
Streaming  not work with xamarin forms

**Comment by TennisDrum** [comment]
I haven't tried any offline processes. But, I have finally gotten subscription streaming working really well - if that's what you're asking about. 

I JUST posted a very long/detailed answer to #162 related to getting a subscription going and having that auto update a ListView. The number link above should get you there. Hope that help.
