### ISSUE TITLE
Cannot find methods like OrderByKey() and StartingAt on firebase client object

### ISSUE THREAD

**Issue by ilivestrong** [step-up-labs/firebase-database-dotnet#123]
Hi,

I have installed latest version of Firebasedatabase.net 3.2.5.

I have created firebase client object and trying to get a specific node. 

```
var userQueryResponse = firebaseClient
                                        .Child("Users")
                                        **.OrderByKey()
                                        .StartAt()**

```
But methods (in bold) are not available.

May be I am missing anything? Please help.

**Comment by bezysoftware** [comment]
Are you missing the using statement?
` using Firebase.Database.Query;`
