### ISSUE TITLE
Synchronization issues with Realtime Database and a possible solution

### ISSUE THREAD

**Issue by MathewSachin** [step-up-labs/firebase-database-dotnet#124]
`RealtimeDatabase` is not receiving streaming events from Firebase except `put` when a new item is added and `keep alive`.

So, when an element is edited no notification is received.

A possible fix is to change the line:
https://github.com/step-up-labs/firebase-database-dotnet/blob/2392df1860971ff188cce305078f97eb78a91e31/src/Firebase/Offline/RealtimeDatabase.cs#L264

to just:
```csharp
var query = this.childQuery; 
```

I suppose the main problem is with the `StartAt` method which is preventing notifications related to any elements whose key appears before the latest key.

**Comment by bezysoftware** [comment]
Which would also mean that if you have 10000 elements in the DB, all of them would need to be fetched each time your app is run. That's not desired

**Comment by MathewSachin** [comment]
I agree that you are right in that way.
But, if I want notification in change of elements, is there any other way.

The data for my application is quite small.
What I'm doing is keeping multiple instances of `RealtimeDatabase` objects and then created `ObservableCollection`s from them.

So, I want to have my `ObservableCollection` up to date with the data on Firebase.

I appreciate your help.

**Comment by bezysoftware** [comment]
I gave it a quick thought and I agree there should be an option to do what you need. I just pushed a change which allow this - use one of the overloads for `AsRealtimeDatabase` which will allow you to specify `StreamingOptions` - and just set it to `Everything`. That should do the trick. 

Here's the commit https://github.com/step-up-labs/firebase-database-dotnet/commit/05aae6c88d142670ec20605e01f95ab06988180b
Nuget will be available once it gets indexed, v3.3.0

**Comment by MathewSachin** [comment]
Thank you! Awesome job.
I'll test the nuget version and let you know.

**Comment by MathewSachin** [comment]
Works perfectly. Thank you!
