### ISSUE TITLE
Subscribe eventhandler fires every 1-2 minutes

### ISSUE THREAD

**Issue by ly4an** [step-up-labs/firebase-database-dotnet#126]
I subscribed to changes on realtime database, but eventhandler fires constantly, about every 1-2 minutes. Database doesn't have any changes.
What is wrong ?

 var observer = firebase
                    .Child("messages")
                    .AsObservable<FirebaseMessage>()
                    .Subscribe(item =>
                    {
Logger.Info("FirebaseMessengerClient called");
});

**Comment by leepsi** [comment]
I have the same problem ! My connection is fine and every 1min40, it fires an event.
Nice to know i'm not alone. I think it's an issue, but not from my connection
