### ISSUE TITLE
Installing on .Net Framework 4 project

### ISSUE THREAD

**Issue by ilivestrong** [step-up-labs/firebase-database-dotnet#128]
Hi Guyz,

Although I have used this library in .Net Core 2 web api, and it works great there.

But I have a requirement, where I need to use this library in a .Net Framework 4 targeting project. I tried to install it using NuGet, but can't seem to get it through. I tried to install an earlier version as well, but it didn't help too.

Could you please suggest, if there is any way/work around this problem?

Thanks in advance.

Deepak

**Comment by jaybowman** [comment]
I don't have any real fix for you. I've used this package in a couple of .net 4.5.2 applications and have not had any problems installing with NuGet. I use VS 2017. Do you get an error when installing? My latest project uses FirebaseDatabase.net version 3.3.2. I would suggest uninstall, make sure you don't have any remaining in your packages folder. Compile you solution and try to add the package again.

**Comment by jaybowman** [comment]
On post #104 bezysoftware says that the minimal support is 4.5. What version of .net 4 is your project targeted for?

**Comment by ilivestrong** [comment]
@jaybowman - Thanks for pointing it out. Originally my app target framework was .Net Framework 4. I changed it to 4.5. Then I installed firebasedatabase.net and it succeeded eventually.

Thanks a ton man, Cheers!
