### ISSUE TITLE
Can't open the source code on Visual Studio 2013

### ISSUE THREAD

**Issue by gregstein** [step-up-labs/firebase-database-dotnet#129]
Hello,

First off, thank you for all this awesome work!!

I'm sorry, but I can't seem to run your source code on Visual studio 2013
Here is what I am getting:

(https://image.prntscr.com/image/EefDv1yHRHSsOXZLdyZ7VQ.png)

**Comment by bezysoftware** [comment]
That doesn't seem to be this library on the screenshot.
