### ISSUE TITLE
Ability to implement paging function

### ISSUE THREAD

**Issue by Calvido** [step-up-labs/firebase-database-dotnet#13]
Do you consider it possible to adopt in the future implementation of paging tools as does the firebase-util library?
[https://github.com/firebase/firebase-util/tree/master/src/Paginate](url)

**Comment by bezysoftware** [comment]
Unfortunately the rest api offers only limited options. You can use `OrderByKey().StartAt(..).TaskFirst()` to have paging, but this approach requires you to start at the beginning (first key) and remember the last key - which is used as the starting point for the next page. 

The API doesn't support skipping "some number" of elements, so the only possible scenario would be infinite scroll.
