### ISSUE TITLE
Lex.db to LiteDB Migration

### ISSUE THREAD

**Issue by cabauman** [step-up-labs/firebase-database-dotnet#130]
@bezysoftware I'm working on the getting rid of the PCL by substituting Lex.db with LiteDB. This project currently targets .netstandard 1.1, but LiteDB only targets down to 1.3. Do you have any issues with increasing the target version to 1.3, or even 2.0? So far, I have the LiteDB version of the OfflineDatabase version working on both Android and iOS.

Reference issue: https://github.com/step-up-labs/firebase-database-dotnet/issues/37

**Comment by bezysoftware** [comment]
Targeting 2.0 should be alright
