### ISSUE TITLE
This library would be amazing if it could be paired with linqpad!

### ISSUE THREAD

**Issue by hmexx** [step-up-labs/firebase-database-dotnet#137]
Would it work out of the box or would it require some modifications?

One of the biggest issues I have with firebase is that writing adhoc queries is a pain in the backside. You need to write node scripts for everything.

I used to use linqpad (http://www.linqpad.net/) to make up for MongoDB's weak querying compared to SQL Server.

Could one do the same thing with firebase and your library?

Thanks!

**Comment by jogleasonjr** [comment]
@hmexx it works for me out of the box in LINQPad.

**Comment by hmexx** [comment]
I assumed it wouldn’t but you’re right. After a bit of setup headache I got it working. This is brilliant! No more node scripts for me.
