### ISSUE TITLE
Equivalent Commands

### ISSUE THREAD

**Issue by wanderson-ra** [step-up-labs/firebase-database-dotnet#138]
What was equivalent to this command in FirebaseDatabase.net considering the structure below?

![1_i_0foogodriqpo3xlkcrpa](https://user-images.githubusercontent.com/7583960/38311062-92cfdc78-37f4-11e8-8b94-daee9d68fad5.png)

`Query query1 = raiz.child("grupos").orderByChild("nome").equalTo("Analise Matematica").limitToFirst(1);`

**Comment by cabauman** [comment]
Query query1 = raiz.Child("grupos").OrderBy("nome").EqualTo("Analise Matematica").LimitToFirst(1);

The only difference is OrderBy = orderByChild
