### ISSUE TITLE
RealtimeDatabase for primitive types

### ISSUE THREAD

**Issue by cabauman** [step-up-labs/firebase-database-dotnet#139]
Do you have a recommended way to handle a RealtimeDatabase for primitive types, such as bool, int, float?

.AsRealtimeDatabase<int> doesn't work because of the class constraint. Is boxing it up in an object and casting the only way?

By the way, I love your work in these Firebase libraries. Thanks a lot for sharing.

**Comment by Transferr3** [comment]
@cabauman did you find a solution ?
