### ISSUE TITLE
How do I enable offilne work?

### ISSUE THREAD

**Issue by wanderson-ra** [step-up-labs/firebase-database-dotnet#142]
Sorry for ignorance, I am new to firebase, I want to enable offilne work in my xamarin forms application, how can I do this using FirebaseDatabase.net?

**Comment by cabauman** [comment]
You can reference: [this issue](https://github.com/step-up-labs/firebase-database-dotnet/issues/140) for a similar question.

There's no "on/off" enabling. You just turn your node reference into a [_RealtimeDatabase_](https://github.com/step-up-labs/firebase-database-dotnet/blob/465d29ad29502c365a4e5053a6ef3d0f2ee0d641/src/Firebase/Offline/RealtimeDatabase.cs) with the _AsRealtimeDatabase_ extension method and then use those methods to sync your online and offline data.

More sample usage in the sample project: [Sample](https://github.com/step-up-labs/firebase-database-dotnet/blob/465d29ad29502c365a4e5053a6ef3d0f2ee0d641/samples/OfflineChat/OfflineChat/Program.cs)

**Comment by cabauman** [comment]
Hi @kormemis. Because PCLs are depreciated, I strongly recommend switching over to a netstandard library (unless something is holding you back?). I'm currently using this offline db with a few of my Xamarin projects and works great.

**Comment by kormemis** [comment]
@cabauman  I changed to .net standard 1.5 and try to install litedb but I cant get success. does litedb is supported by .net standard 1.5 ?

**Comment by cabauman** [comment]
Ah, this project targets netstandard 2.0 now. Migrated when we switched to litedb: [https://github.com/step-up-labs/firebase-database-dotnet/issues/130](https://github.com/step-up-labs/firebase-database-dotnet/issues/130)

**Comment by kormemis** [comment]
@cabauman  oh ok then , do you have a plan to make a xamarin sample ?

**Comment by cabauman** [comment]
@kormemis  Yeah, I've thought about putting a sample together and making a pull request here. I guess it wouldn't take too long to do something simple. I'll try to do one soon.

**Comment by kormemis** [comment]
@cabauman thank you very much 👍

**Comment by cabauman** [comment]
@kormemis forms or native?

**Comment by kormemis** [comment]
using forms. and I'm trying to use offline sync I'm getting error something like this 
`/Users/mehmeterdil/Projects/RinoHub/RinoHub/MainPage.xaml.cs(64,64): Error CS0266: Cannot implicitly convert type 'Firebase.Database.Offline.OfflineDatabase' to 'System.Collections.Generic.IDictionary<string, Firebase.Database.Offline.OfflineEntry>'. An explicit conversion exists (are you missing a cast?) (CS0266) (RinoHub)
/Users/mehmeterdil/Projects/RinoHub/RinoHub/MainPage.xaml.cs(64,64): Error CS1662: Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type (CS1662) (RinoHub)`

**Comment by cabauman** [comment]
Can you link me to your project so I can try to reproduce it?

**Comment by kormemis** [comment]
@cabauman  actually I fix it after a restart, everything works also offline database. when you start online and get authenticated and get offline , there is no problem. but when you started offline , token gets null and so firebase client object not created. so it gives error when I try to start project as offline. I think there is a bug.

**Comment by wanderson-ra** [comment]
@cabauman Would you have a more complete example of how to implement real-time functionality with some nosqldb? Can you help me?

**Comment by cabauman** [comment]
@wanderson-ra @kormemis here's a Xamarin Forms example using the offline functionality: https://github.com/cabauman/firebase-database-dotnet/tree/xamarin_forms_sample

**Comment by kormemis** [comment]
@cabauman  hello colt , I tried , works offline perfect , but I cant pull and push from the firebase database even I put the link and api key to the sample. Did I something wrong ?

**Comment by cabauman** [comment]
@kormemis sorry, I’m not sure what the problem could be. Pushing and pulling online works for me with the Xamarin sample.

**Comment by dannykhreet** [comment]
@cabauman  on your xamarin form project , the offline database work currect but if i change on the firebase online database the offline database doesnt get the changes ?

**Comment by cabauman** [comment]
@dannykhreet I haven't updated the project to reflect these changes yet, but see if this solves your issue: [https://github.com/step-up-labs/firebase-database-dotnet/issues/154#issuecomment-406571397](https://github.com/step-up-labs/firebase-database-dotnet/issues/154#issuecomment-406571397)

Calling _PullAsync()_ on the realtime database is required to get the latest changes from online.

**Comment by hgfilho** [comment]
on line
"OfflineDatabaseFactory = (t, s) => new OfflineDatabase(t, s),"
appears "OfflineDatabase can be found".

**Comment by 420tech** [comment]
I pulled the Xamarin example. I created a Firebase project and updated web api keys and url to database. The offline db works fine - but no entries ever got pushed to the cloud. What am I doing wrong?
