### ISSUE TITLE
How to update an object ?

### ISSUE THREAD

**Issue by dogczar** [step-up-labs/firebase-database-dotnet#144]
How to update an object ?

**Comment by ElishaMisoi** [comment]
Did you find a way of updating an object?

**Comment by bezysoftware** [comment]
```
await firebase
  .Child("dinosaurs")
  .Child("t-rex")
  .PutAsync(new Dinosaur());
```

**Comment by ElishaMisoi** [comment]
Thanks for the reply. PutAsync() ovewrites everything in the node. What if
I want to update a single path in an an object node. Say just updating
'name' in a user object.

**Comment by ElishaMisoi** [comment]
I really love your work. It's the only Firebase client I use for Xamarin.

The problem I was having is updating a single path in an object node. Now I
have to use OnceSingleAsync() to get the object data that was initially in
the object node then updating the path I want and use PutAsync() to update
the entire node again because if I update a single path by creating a new
object it overwrites the entire node.

Wish you could add support for updating a single path in an object node.

Or I am missing something, maybe?

**Comment by bezysoftware** [comment]
Why can't you add another child like this?

```
await firebase
  .Child("dinosaurs")
  .Child("t-rex")
  .Child("description")
  .PutAsync("Big t rex");
```

Or as I wrote you can use `PatchAsync` which will overwrite only those fields which are present in the json payload. You can combine this with JSON.net's DefaultValueHandling to serialize only non-default values (e.g. null's will not be serialized), you `new` the object you want, set only properties you want (leaving others null) and that will work

**Comment by ElishaMisoi** [comment]
Okay, thank you, let me try that out.

**Comment by ElishaMisoi** [comment]
Using PatchAsync() with JsonIgnoreDefaultValues did it for me.

I was trying to upload media to Storage bucket and updating 'resource_url'
in a 'message' object in the the database.

I still do not get why PutAsync(resource_url) threw an invalid data
exception even though the URL was in string format.

Anyway, thanks for the help, using PatchAsync() with
JsonIgnoreDefaultValues worked.

**Comment by lucazin** [comment]
Hello!

How can i update just a name in my node?

im using this

  // the base reference
                var referencia = firebaseClient.Child("ESTABID_17").Child("PEDIDOS_DELIVERY").Child("-Lzhy-dZ9iFiJ823q9sMQ");
                // create an user with a specif key
                await referencia.Child("codigoPedido").PatchAsync("ola");

but i have a error in url json format.

**Comment by gadiman** [comment]
Because Firebase expects to get a string in JSON format:

 string jsonData = @"{""name of node to update"":  "" new value "" }";

            await firebase
                   .Child(youre path)
                   .Child(youre path)
                   ......
                   ......
                   ......
                   .PatchAsync(jsonData);
