### ISSUE TITLE
Listening for updates on a single object by Key

### ISSUE THREAD

**Issue by mcurrycl** [step-up-labs/firebase-database-dotnet#145]
I am trying to use the library to listen for updates against a single database object. My workflow so far has been to create an object on the firebase database (using PostAsync), getting the new key, and then creating an Observable using "AsObservable" listening on the key as a child:

````
public class Account
{
    public string surname;
    public bool isReceived;
    public string id;
}

var fb = new FirebaseClient(url);
var res = fb.Child("accounts").PostAsync(new Account() {surname="Smith", isReceived=false, id=""};
var ob = fb.Child("accounts").Child(res.Key).AsObservable<Account>();
....
ob.Subscribe(d => Console.WriteLine("Processing:" + d.isReceived);
....
Console.ReadLine();
````

When the event comes from the server, I get a "JsonSerializationException" somewhere up the chain. I think this is because it is trying to deserialize a property of the "Account" object JSON into an account object, rather than the whole object (unable to convert "surname" to type Account).

I can get it to work fine if I drop the ".Child(res.Key)" method and instead use a "Where" clause, but this returns all of the accounts in the database and just filters them on the client side. For security and speed I just want to listen for changes on the Account I just created.

**Comment by bezysoftware** [comment]
You should be able to use `AsObservable` method with the `elementRoot` parameter (equal to the key of your object you want to observe).
