### ISSUE TITLE
suscribe instructions never work when change value of patch

### ISSUE THREAD

**Issue by Charly290909** [step-up-labs/firebase-database-dotnet#147]
my base is https://geo-notifications.firebaseio.com/TestBoson
which only has a text string as property then I want to identify when this value changes to continue with the process:

client = new FirebaseClient ("https://geo-notifications.firebaseio.com/");

  observable var = client
            .Child ("TestBoson")
           .AsObservable <Firelement> ()
          .Subscribe (d => Console.WriteLine (d.Key));

my FireElement class contains only one string property
the problem is that I modify the value and launch the console writeline instruction
what is the solution?

**Comment by Mikelantonio** [comment]
I confirm. I have the same issue

**Comment by Charly290909** [comment]
hi man i using firesharp is better!
________________________________
De: Michelantonio Trizio <notifications@github.com>
Enviado: viernes, 22 de junio de 2018 11:11 a. m.
Para: step-up-labs/firebase-database-dotnet
CC: Charly290909; Manual
Asunto: Re: [step-up-labs/firebase-database-dotnet] suscribe instructions never work when change value of patch (#147)


I confirm. I have the same issue

**Comment by bezysoftware** [comment]
AsObservable primarily works with collections. If you want to use it to observe single value, you need to tell it in the AsObservable method: 
```
.AsObservable(elementRoot: "TestBoson")
```
Then it should work. There is also a second parameter `"exceptionHandler"` which would tell you there was an exception being thrown

**Comment by Ishmael-Moreno** [comment]
Hey @bezysoftware  i tried what you suggested however i'm getting the error stated bellow
![capture](https://user-images.githubusercontent.com/42048275/43613703-6dedb8c4-967e-11e8-816d-8faeb253ead7.PNG)
 Am i doing something wrong?

   var observable = firebase
                  .Child("chatservice")
                  .AsObservable(elementRoot: "chatservice")
                  .Subscribe(d =>
                  MessageBox.Show(d.Key)
                  );

**Comment by cabauman** [comment]
@Ishmael-Moreno like in the [chat sample project](https://github.com/step-up-labs/firebase-database-dotnet/blob/bc8e5501aed2acc51af6aca416f4c63331f52f67/samples/ConsoleChat/ConsoleChat/Program.cs#L27), you just have to add the generic type argument like

`AsObservable<ChatService>(elementRoot: "chatservice")`

so it knows what kind of object it's dealing with.
