### ISSUE TITLE
Max 2 subscriptions can be active

### ISSUE THREAD

**Issue by VictorPechersk** [step-up-labs/firebase-database-dotnet#15]
This is because FirebaseSubscription class uses single HttpClient instance for all subscriptions, however for HTTP 1.1 you have maximum of 2 TCP connection per host (e.g. server) that can be active (see https://social.msdn.microsoft.com/Forums/en-US/1f863f20-09f9-49a5-8eee-17a89b591007/asynchronous-httpwebrequest-maximum-connections-best-approach-threads-or-delegates?forum=netfxnetcom).

**Comment by bezysoftware** [comment]
It doesn't matter if the implementation uses a single HttpClient or multiple clients - that's a limitation of the platform and the link provides details how to bypass it

**Comment by kingsurf** [comment]
I am also having this problem if I run this code in my console application

```
           var observable2 = firebase
              .Child("furniture2")
              .AsObservable<Furniture>()
              .Subscribe(d =>
              {
                  Console.WriteLine($"Furniture2 modified {d.Key}");
              });

            var observable1 = firebase
              .Child("furniture")
              .AsObservable<Furniture>()
              .Subscribe(d =>
              {
                  Console.WriteLine($"Furniture1 modified {d.Key}");
              });

```

I also have this in my app.config


```
  <system.net>
    <connectionManagement>
      <add address="https://onebook-1f2ce.firebaseio.com" maxconnection="200" />
      <add address="*" maxconnection="200" />
    </connectionManagement>
  </system.net>
```

Still only one subscription is executed...

**Comment by bezysoftware** [comment]
As I said, it doesn't matter if a single `HttpClient` is used, or multiple instances are used - this is limitation of the operating system on per `AppDomain` basis. If you need to up the limit, you can use something like this:

`ServicePointManager.DefaultConnectionLimit = 100; // default is 2`

I just tested in Console app with three subscriptions, without this line I had only 2 of them active, with is I had all 3 active.
