### ISSUE TITLE
Subscribe observable not receive changes after sleep or hibernet

### ISSUE THREAD

**Issue by vdhong** [step-up-labs/firebase-database-dotnet#150]
Hi there,
I used this package and it worked good. My app can receive changes from FB by using this code:
```
client.Child("Alerts").AsObservable<T>()
                    .SubscribeSafe(actionEvent);
```
But after my PC wake up after sleep, my app does not receive any change from firebase (I change manual on FB for test).
So what should I do to continue receiving changes from FB after sleep?
Thank you!

**Comment by jcaruso001** [comment]
@vdhong Can you post your actionEvent for us to look at?

**Comment by bezysoftware** [comment]
I can confirm this behavior, marking it as a bug

**Comment by vdhong** [comment]
Here my class of actionEvent object
`public class ListenChanges<T> : IObserver<FirebaseEvent<T>>
    {
        public bool IsCompletedObserver { get; private set; }

        public void OnCompleted()
        {
        }

        public void OnError(Exception error)
        {
            //log error
        }

        public void OnNext(FirebaseEvent<T> value)
        {
            //process value
        }
    }`

**Comment by AchuthanR** [comment]
Hi, I am also facing the same issue. Is there a known fix for this? Or can I handle it in any way?
It would be useful to at least know why this happens. Thanks in advance!

**Comment by AchuthanR** [comment]
I went through the code and found this line (link attached below) to be the cause of this issue.
Probably some time after the PC goes to sleep the server stops sending events. After the PC wakes up, reader.ReadLine() blocks and doesn't time out. The CanTimeout property for the underlying stream returns false. Does anybody know a way to set a timeout for this stream? Setting a timeout of 100s might be ideal as, in my observation, the server sends keep-alive event approximately every 30s. So, the streaming can be restarted if it times out.

https://github.com/step-up-labs/firebase-database-dotnet/blob/66716f87a392f32fc0711bd1b8b9c0956646c422/src/Firebase/Streaming/FirebaseSubscription.cs#L108

**Comment by abdoutech93** [comment]
any update for this issue, I confirm this behavior
