### ISSUE TITLE
offline sync help 

### ISSUE THREAD

**Issue by kormemis** [step-up-labs/firebase-database-dotnet#154]
hello guys I'm trying to develop offline-first application on xamarin 

but I have some questions about the progress. 
first of all , I check the @cabauman 's sample on xamarin. it works well on offline db. project save offline data to local storage and send the values to firebase. it is ok till here. 

But when I try to delete a post on firebase database dashboard. and refresh , or restrart the project , that deleted post still there. 

I want to create an app that can works on multiple devices , when a user deletes or updates something that changes on their own devices and when other device is connected that change should appear on another device. 

I understand like that the device is master , any changes on firebase dashboard not affected the application's local db 

can you offer me a sample code on this scenerio ? 

thanks.

**Comment by cabauman** [comment]
I haven't run the project lately. I'll try and let you know what I find this week sometime.

**Comment by kormemis** [comment]
it works thank you very much

**Comment by kormemis** [comment]
@cabauman  hello colt why PullAsync() gives ' Sequence contains no elements' error ? do you have an idea ?

**Comment by cabauman** [comment]
No, sorry. I have never encountered that error.

**Comment by kormemis** [comment]
I wrote wrong code sorry , it is all working now
