### ISSUE TITLE
Subscription for non existing data does not work

### ISSUE THREAD

**Issue by VictorPechersk** [step-up-labs/firebase-database-dotnet#16]
If to subscribe to a non existing path in Firebase it will invoke callback with null value. However FirebaseDatabase library does not notify subscribers at all.
ProcessServerData method of FirebaseSubscription class must call this.observer.OnNext also when items collection is empty.

**Comment by bezysoftware** [comment]
What exactly should the OnNext be called with? Insert with null? In my opinion that doesn't make sense - you should only be notified when there is some data

**Comment by VictorPechersk** [comment]
Yes, called with null value. This is how Firebase JS library works. In this case we will know exact that this path is not present, otherwise we don't know whether there are no data or data present and we will receive them few later.

**Comment by bezysoftware** [comment]
That makes sense, I'll put it on my todo list

**Comment by bezysoftware** [comment]
Should be resolved with latest commit, reopen if you find any issues
