### ISSUE TITLE
How to get the data through the instance of AsRealtimeDatabase <T> (...)?

### ISSUE THREAD

**Issue by marciliocarvalho** [step-up-labs/firebase-database-dotnet#161]
I am using the FirebaseDatabase.net offline database. In it I can enter data, update and delete. However, I can not get data through the instance of AsRealtimeDatabase <T> (...).
Does anyone know how to do it?

**Comment by cabauman** [comment]
1. **Once()**
```
    // Call PullAsync if you want to sync your offline database with the online one.
    await authorsDb.PullAsync();

    IEnumerable<Author> authors = authorsDb
        .Once()
        .Select(x => x.Object);
```

2. **Access the dictionary and deserialize manually**

```
    Author author = null;
    bool success = authorsDb.Database.TryGetValue("object_key", out OfflineEntry offlineEntry);
    if(success)
    {
        author = offlineEntry.Deserialize<Author>();
    }
```

3. Subscribe to streaming events using **AsObservable()**
```
    authorsDb.AsObservable()
        .Where(x => !string.IsNullOrWhiteSpace(x.Key))
        .Subscribe(
            firebaseEvent =>
            {
                Console.WriteLine(firebaseEvent.Object.Name + ": " + firebaseEvent.EventSource);
            });
```

4. **AsObservableCollection()**
```
    ObservableCollection<Author> authorCollection =  authorsDb
        .AsObservable()
        .AsObservableCollection();
```

**Comment by marciliocarvalho** [comment]
It worked. The problem was that the AsRealtimeDatabase method was getting a wrong parameter.
However, I am not able to recover the data properly when I am offline. Would you know how to do it?

**Comment by Fabricciotcortes** [comment]
Can i put   " ObservableCollection<Author> authorCollection =  authorsDb
        .AsObservable()
        .AsObservableCollection();" In a List to view in a DataGrid?.

In summary i try to get a real time data from Firebase with the API FireBaseDataBase, as a List() because i want to insert in my Datagrid.

**Comment by marciliocarvalho** [comment]
Also, I realized that the token can not be received when the system is offline, getting equal to null. I think that's what's causing the problem ...

The following is the DB initialization code:

```
public static async Task IniciarBD()
        {
            try
            {
                auth = new FirebaseAuthProvider(new FirebaseConfig(firebaseApiKey));

                try
                {
                    token = await auth.SignInWithEmailAndPasswordAsync("mar@mar.com", "123456");
                }
                catch
                {
                    token = null;
                }

                firebaseClient = new FirebaseClient(
                firebaseUrl,
                new FirebaseOptions
                {
                    AuthTokenAsyncFactory = () => Task.FromResult(token.FirebaseToken),
                    OfflineDatabaseFactory = (t, s) => new OfflineDatabase(t, s)
                });



                try
                {
                    userUID = auth.GetUserAsync(token).Result.LocalId;
                }
                catch
                {
                    Console.WriteLine("Offline");
                    Console.ReadLine();
                }



            }
            catch (Exception ex)
            {
                Console.Write(ex);
                Console.ReadLine();
            }
        }
```

**Comment by cabauman** [comment]
You have to detect if the user is connected to the internet. If not, don't call PullAsync.

**Comment by marciliocarvalho** [comment]
@cabauman , thanks for the tip. But why is it that when I'm out of the internet and I'm not calling PullAsync (), my returned values are all wrong?

**Comment by cabauman** [comment]
Because if the user isn’t online, they’ll just getting the stored offline values, which may not be synced with the online values.

**Comment by cabauman** [comment]
@marciliocarvalho  Okay, I see what's going on. The offline database stores a dictionary of objects and uses the _data type_ as the filename. So each time through your loop, the "PullAsync" _overwrites_ what was there before. As Bezy said in [this post comment](https://github.com/step-up-labs/firebase-database-dotnet/issues/45#issuecomment-284232564), if you want to store multiple lists of the same data type, you have to use the _filenameModifier_ parameter of **AsRealtimeDatabase** to differentiate it from the other files:
https://github.com/step-up-labs/firebase-database-dotnet/blob/bc8e5501aed2acc51af6aca416f4c63331f52f67/src/Firebase/Offline/DatabaseExtensions.cs#L22

So make it something unique, like the date:

`AsRealtimeDatabase<object>(currentDate.ToString(), "", StreamingOptions.Everything, InitialPullStrategy.Everything, true);`

**Comment by marciliocarvalho** [comment]
@cabauman
friend, thanks for the help. It worked!
