### ISSUE TITLE
JsonSerializerSettings are ignored for RealtimeDatabase requests

### ISSUE THREAD

**Issue by adolgov** [step-up-labs/firebase-database-dotnet#164]
I'm trying to Patch a `RealtimeDatabase` entry, and am using `DefaultValueHandling.Ignore` `JsonSerializerSettings` option; however, it seems to be overwriting data with defaults.

Is this the correct way to ignore defaults when using offline/online style for firebase (i.e. using `RealtimeDatabase` rather than `ChildQuery`)?

**Comment by cabauman** [comment]
Hmm, I would have to see your code. I have successfully used the Ignore option for patching.

**Comment by adolgov** [comment]
I will try to come up with a simplified code example that will exhibit this behavior.

**Comment by cabauman** [comment]
Okay I thought this was working for me but I guess not. It works for PatchAsync but not the offline version. @bezysoftware are we missing something?

**Comment by bezysoftware** [comment]
I think this might be the cause: https://github.com/step-up-labs/firebase-database-dotnet/blob/master/src/Firebase/Offline/OfflineEntry.cs#L113

The options are not passed to the OfflineEntry instance.

Using [IgnoreAttribute] should work

**Comment by cabauman** [comment]
Thanks Tomas. As an experiment I passed the options into my patch call and used them here in the [OfflineEntry constructor](https://github.com/step-up-labs/firebase-database-dotnet/blob/9652f249b9c167f1e9ed17664d0c22e67cc872f1/src/Firebase/Offline/OfflineEntry.cs#L41) and it works.

I don't want to completely ignore any of the properties with the IgnoreAttribute, but I'll play around with different configurations.
