### ISSUE TITLE
Crash with "Too many open files" error when RealtimeDatabase data count gets large

### ISSUE THREAD

**Issue by adolgov** [step-up-labs/firebase-database-dotnet#166]
I have a long-running app that constantly pushes data to Firebase via the Online/Offline ReatimeDatabase calls. I noticed that if I run the app for a day or two (it generates small data entries every 5 secs or so), the app will crash. When I start it up again, it will continue to crash until I clear out the dataset.  The number of total data entries doesn't seem exceptionally huge (a few thousand).

This only seems to happen when `pushChanges` option is `true` for the RealtimeDatabase.

I made a simple code snippet to replicate this behavior quickly by inserting data at 10Hz:
```
tests = client.Child(userID).Child("test");

//await tests.DeleteAsync();

testsDb = tests.AsRealtimeDatabase<TestData>(
    filenameModifier: "",
    elementRoot: "",
    streamingOptions: StreamingOptions.None,
    initialPullStrategy: InitialPullStrategy.Everything,
    pushChanges: true);

Observable.Timer(TimeSpan.FromSeconds(10), TimeSpan.FromMilliseconds(100))
    .Subscribe(_ =>
    {
        if(testsDb.Database.Count % 10 == 0)
        {
            _log.Debug($"Posting Test. Total: {testsDb.Database.Count}");
        }
        var t = new TestData() { Name = "test", Data = 40f, Time = DateTimeOffset.UtcNow };
        testsDb.Post(t);
    });
``` 

After the first crash, the subsequent application starts (when the DB attempts the initial sync) fails upon the first attempt to insert a new data entry.

Potentially related (but not 100% sure): As the dataset fills up, I tend to see more frequent "Collection was modified; enumeration operation may not execute." Exceptions of type `System.InvalidOperationException`.
I don't have hard stats about the increased frequency of this exception, since I do see it periodically pre-crashes; however, it does seem that the frequency does increase as the amount of stored data increases.

Client set-up and above test-code is in a NetStandard 2.0 library, while the overall application is Xamarin.Android.

**Comment by bezysoftware** [comment]
It appears to be 2 separate issues. One issue is that there is a memory leak which causes the memory to get out of control after just a few minutes. I believe I found it and fixed it. 

The exception you're seeing should be resolved by using ConcurrentOfflineDatabase
```
new FirebaseOptions 
{
   ...
   OfflineDatabaseFactory = (t, s) => new ConcurrentOfflineDatabase(t, s)
}
```

**Comment by bezysoftware** [comment]
Memory leak should be fixed in beta3, can you try?

**Comment by adolgov** [comment]
Thanks. I'll run the app over the weekend. Hopefully, the issue has been resolved.

**Comment by adolgov** [comment]
Seems like it's running happily for a few days now. Older version would have definitely crashed by now. I'll keep an eye on it, but assuming it's fixed. Thanks!
