### ISSUE TITLE
Hanging on second query

### ISSUE THREAD

**Issue by leelenini64** [step-up-labs/firebase-database-dotnet#167]
Hi, I'm trying to use this library for a simple query. I have some information nested down a few levels, and I'm trying to get the double value here:
`var baseline = await database.Child("baselines")
            .Child(parentClass).Child(name).Child(newString)
            .Child(machine).OnceSingleAsync<double>();`

This query is in a function which gets called multiple times over the course of a class as it iterates through a list of strings. This works fine for the first call, but the second time it executes, the application just hangs. I've let it sit for 5+ minutes and it still doesn't return a value. The database I'm querying has fewer than 10 cases. Any idea what I'm doing wrong?

**Comment by leelenini64** [comment]
Just to update - I fixed the problem by adding `.ConfigureAwait(continueOnCapturedContext:false);` to the call. Found this answer on StackOverflow [here](https://stackoverflow.com/questions/9895048/async-call-with-await-in-httpclient-never-returns).

**Comment by bezysoftware** [comment]
Thanks for the solution link!
