### ISSUE TITLE
Push many items at once

### ISSUE THREAD

**Issue by sessio** [step-up-labs/firebase-database-dotnet#17]
Is there a way to push a collection of items at once, e.g. `PostAsync(IEnumerable<Dinosaur>)` with online or offline -generated object keys?

**Comment by sessio** [comment]
Ok, good to know i haven't missed anything. Thanks!

**Comment by leontyr** [comment]
Is there any chance this will be implemented?

**Comment by cabauman** [comment]
This is how I do it:

    public async Task Add(IEnumerable<T> items)
    {
        return _baseQuery
            .PatchAsync(items.ToDictionary(_ => FirebaseKeyGenerator.Next()))
    }

Or use PutAsync if you want to overwrite everything at that node.
