### ISSUE TITLE
Calling PatchAsync twice raises InvalidOperationException

### ISSUE THREAD

**Issue by brainchest** [step-up-labs/firebase-database-dotnet#173]
**Problem Description**
An InvalidOperaionException is thrown when GetClient() in type FirebaseQuery is called twice. The reason is that in any case the timeout of the client is set. Even if the same timeout is set again then the exception is thrown because the client only allows to set this value once. Exception:

System.InvalidOperationException: 'This instance has already started one or more requests. Properties can only be modified before sending the first request.'

I think setting the timeout either is done only once, or every request should get the timeout.

**Steps to Reproduce**
Call FirebaseQuery.PatchAsync twice

**Environment**
FirebaseDatabase version: latest from GitHub
VS2017
.net 2.0

**Comment by bezysoftware** [comment]
Thanks for the issue, I am aware of it and will be fixed in next nuget deploy
