### ISSUE TITLE
GeoQuery?

### ISSUE THREAD

**Issue by carlosmacmar** [step-up-labs/firebase-database-dotnet#177]
Hi,

I need to create a geoQuery (like GeoFire i.e.), do you know if there is any way to do this in C#?

Thank you :)

**Comment by masodev** [comment]
Hey @carlosmacmar 

The only "answer" I could find is:
https://stackoverflow.com/questions/51078938/using-geofire-in-xamarin-forms

and a possible solution:
https://github.com/sidesoftware/SideGeoFire

Just posting in case you have not seen it already!
