### ISSUE TITLE
Help with subscribe node is exist or not

### ISSUE THREAD

**Issue by halilpolathalil** [step-up-labs/firebase-database-dotnet#178]
Hello,
I need little help with subscribe. Here is my code:
 string node = "751308/classrooms";
 var observable =  firebase.Child(node).AsObservable<Student>().Subscribe();

I need to listen İf given node is deleted or exist.
But I dont have any idea how I can do this. I did not used  subscribe method.
Can anyone give an example for subscribe?

By the way my code give an exception "Could not load file or assembly 'System.Reactive.Linq, Version=3.0.1000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies."

Thanks for help. Sorry for bad english.

**Comment by bezysoftware** [comment]
Try the latest beta, it has a dependency on System.Reactive v4
