### ISSUE TITLE
Subscribe for list

### ISSUE THREAD

**Issue by VictorPechersk** [step-up-labs/firebase-database-dotnet#18]
Let's say we have such list
{
 data:
 {
   key1: "x",
   key2: "y",
   key3: "z"
 }
}

How to subscribe for data and get its all content as dictionary?

If in AsObservable pass dictionary type it does not work, if pass string type I receive "key1":x, "key2":"y", "key3":"z" separately.

Thanks.

**Comment by bezysoftware** [comment]
What is your use case scenario? If the structure is static you just need a class with sub keys as properties of that class.

**Comment by VictorPechersk** [comment]
Tomas, this is not a static structure, this is variable list of items with various keys. So I need to get this whole list on each change.

**Comment by bezysoftware** [comment]
I just tested briefly and you're correct, subscribing with a Dictionary doesn't work currently. I'll put that on my todo list

**Comment by bezysoftware** [comment]
You can now subscribe to a location with dictionary and have it treated as a single dictionary value which will produce an event on each change. It requires a slight change in the AsObservable method:

```
client
 .Child("data")
 .AsObservable<Dictionary<string, string>>(elementRoot: "data");
```
By specifying element root you give the subscriber a hint that the given location ("data") doesn't contain a list of dictionaries, but it is a single dictionary.
