### ISSUE TITLE
Changes on Database not captured by Subscribe.

### ISSUE THREAD

**Issue by masodev** [step-up-labs/firebase-database-dotnet#181]
var observable = client
  .Child("appointments")
  .AsObservable<dataAppointment>()
  .Subscribe(d => Console.WriteLine(d.Key));

Any changes I make do the database do not call the subscribe method, anyone else having this issue?

**Comment by kormemis** [comment]
how about FirebaseOptions. did you subscribe an offline db or online db ? 
can you post your FirebaseOptions code ?

**Comment by masodev** [comment]
Hey there @kormemis, not using any FirebaseOptions other than Auth, the db
is online. Could you post an example of how the FirebaseOptions should be
for persistance?

**Comment by kormemis** [comment]
```
var firebaseClient = new FirebaseClient(
  "<URL>",
  new FirebaseOptions
  {
    AuthTokenAsyncFactory = () => LoginAsync()
  });

...

public static async Task<string> LoginAsync()
{
  await authProvider.SignInWithEmailAndPasswordAsync("yourloginemail","yourpassword")
}


firebaseclient.Child("YourNode").AsObservable<"YourModel">().Subscribe(a => Console.WriteLine(a.Key + " " + a.EventSource + " " + a.EventType);

```


try to login with an authentication. And then try with this.
