### ISSUE TITLE
AsRealtimeDatabase Filtering

### ISSUE THREAD

**Issue by masodev** [step-up-labs/firebase-database-dotnet#183]
Using:
var messagesDb = client.Child("dinosaurs").AsRealtimeDatabase<Message>();
returns all the dinosaurs, any way to selectively filter and retrieve only dinosaurs of a specific type or equals to a specific property?

Something like OrderBy("height").EqualTo(500) but AsRealtimeDatabase.

**Comment by bezysoftware** [comment]
AsRealtimeDatabase gives you an `IObservable` which you can filter / map etc. using standard Linq extensions - Where, Select, etc. I think they live in `System.Reactive.Linq namespace`

**Comment by masodev** [comment]
Hey there @bezysoftware,  thanks for the reply! 

I'm trying to avoid downloading all the data and then filter, is there any way you can think of to filter before downloading?

**Comment by cabauman** [comment]
You could probably add a method like the following that would use the inner child query:

    public async Task<IEnumerable<FirebaseObject<T>>> OnceAsync(Func<ChildQuery, ParameterQuery> filter)
    {
        var query = filter.Invoke(this.childQuery);
        ...
    }

and call it like

    var result = await OnceAsync(x => x.OrderByKey().LimitToFirst(5));
