### ISSUE TITLE
Subscirbing to multiple firebase child not returning values on the 4th and up Subscriber

### ISSUE THREAD

**Issue by MichaelReyes** [step-up-labs/firebase-database-dotnet#184]
Created a function to handle all my firebase observers.

`
void getRealTimeData(String node, IDisposable subscriber, CallType callType) {

            //Dynamically getting data from firebase based on the node set
            var child = client.Child(node);

            Console.WriteLine("node: " + node);

            //create rx observable
            var observable = child.AsObservable<Object>();

            subscriber = observable                       
                //.Where(f => !string.IsNullOrEmpty(f.Key)) // you get empty Key when there are no data on the server for specified node                
                .Subscribe(f =>
                    callBack.onDataLoaded(f.Object, f.EventType.ToString(), callType)
                );
          
        }
`

was working fine but when this functions is called like more than 4 times to subscribe to different firebase child, the 4th and above subscribers don't work anymore and not returning a value.

**Comment by mkbg8** [comment]
I am experiencing the same problem, some subscribers getting the data immediately, others getting it after something like 90 seconds. It appears like the SendAsync in FirebaseSubscription.ReceiveThread is taking a very very long time (i.e. the "var response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, this.cancel.Token).ConfigureAwait(false);" line).
Any ideas?
