### ISSUE TITLE
Is possible use onDisconnect?

### ISSUE THREAD

**Issue by leo0307vb** [step-up-labs/firebase-database-dotnet#19]
I want to know if is possible use logic like onDisconnect to set the lastOnline timestamp. like this:

`var userLastOnlineRef = firebase.database().ref("users/joe/lastOnline");`
`var userStatusRef = firebase.database().ref("users/joe/status");`
 `userLastOnlineRef.onDisconnect().set(firebase.database.ServerValue.TIMESTAMP);`
 `userStatusRef.onDisconnect().set("offline");`

or how could I do it?

thanks.

**Comment by itswisdomagain** [comment]
A rough thought...
You could create a web service that constantly attempts to connect with your app (or that is always connected to your app); if that connection is broken, your web service can then update the specified nodes on Firebase.

You can provide a means to specify the nodes of interest when initializing the service.

Sounds like a hack that can work. Let me know?
