### ISSUE TITLE
Realtime Streaming Silently Stopped

### ISSUE THREAD

**Issue by kwl1990** [step-up-labs/firebase-database-dotnet#190]
using Firebase.Database;
using Firebase.Database.Query;
...
var firebase = new FirebaseClient("https://dinosaur-facts.firebaseio.com/");
var observable = firebase
  .Child("dinosaurs")
  .AsObservable<Dinosaur>()
  .Subscribe(d => Console.WriteLine(d.Key));

I am using above example method to get the real time streaming in my window service and its working..
but when the window service run after a period, the window service status still show running, but i found out that the realtime straming actually silently stopped and not running at all... May i know what may cause this kind of issue ?? Thanks...

**Comment by fabricciotc** [comment]
Try to use MessageBox.Show(d.Key) of course if u are using a windows forms app. The method only works when u run the app and when u update ur database

**Comment by SpajicM** [comment]
I'm having the same issue.

It works for fine for few hours, but randomly stops.

Then I have to do startListening() and stopListening() manually with form buttons, to force it to recieve the messages that got left behind.

My code: https://pastebin.com/snwr9LCN @bezysoftware

**Comment by nonpensavo** [comment]
No fix on this?
