### ISSUE TITLE
WPF - Listen Streaming Data in a Datagrid

### ISSUE THREAD

**Issue by fabricciotc** [step-up-labs/firebase-database-dotnet#191]
¿How i can update a list for my datagrid with streaming data?

**Comment by TennisDrum** [comment]
Check out the answer I just posted to #162. It's for a ListView, but the same concepts should apply.

**Comment by MaablabsTech** [comment]
> ¿How i can update a list for my datagrid with streaming data?

Please help me i have an issue of that kind i see you got a solution and below i have attached my stackoverflow Thread;
https://stackoverflow.com/questions/62458993/system-invalidoperationexception-the-current-thread-has-no-dispatcher-associat
