### ISSUE TITLE
Package installetion

### ISSUE THREAD

**Issue by muxammed** [step-up-labs/firebase-database-dotnet#193]
Hi please advice me whats wrong in installation package 
VS2015 I'm new in C# )))
Could not install package 'FirebaseDatabase.net 4.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.
5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package auth
or.

**Comment by bezysoftware** [comment]
In the main Readme file it says this lib tarhlgerts netstandard 2.0 & has a link to the compatibility matrix - https://github.com/dotnet/standard/blob/master/docs/versions.md
There is shows that v2. 0 is only compatible with net framework 4.6.1

**Comment by muxammed** [comment]
And this is after update
Install-Package FirebaseDatabase.net
Attempting to gather dependency information for package 'FirebaseDatabase.net.4.0.1' with respect to project 'www_arci', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for package 'FirebaseDatabase.net.4.0.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'FirebaseDatabase.net.4.0.1'
Resolved actions to install package 'FirebaseDatabase.net.4.0.1'
Install failed. Rolling back...
Package 'FirebaseDatabase.net.4.0.1' does not exist in project 'www_arci'
Package 'FirebaseDatabase.net.4.0.1' does not exist in folder 'C:\Users\User\Desktop\www_arci - Copy\packages'
Install-Package : Could not install package 'FirebaseDatabase.net 4.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v
4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package 
author.
At line:1 char:1
+ Install-Package FirebaseDatabase.net
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by bezysoftware** [comment]
From the linked doc:


The versions listed here represent the rules that NuGet uses to determine whether a given .NET Standard library is applicable. While NuGet considers .NET Framework 4.6.1 as supporting .NET Standard 1.5 through 2.0, there are several issues with consuming .NET Standard libraries that were built for those versions from .NET Framework 4.6.1 projects. For .NET Framework projects that need to use such libraries, we recommend that you upgrade the project to target .NET Framework 4.7.2 or higher.

Can you test try that?

**Comment by muxammed** [comment]
yes this is it
Install-Package FirebaseDatabase.net
Attempting to gather dependency information for package 'FirebaseDatabase.net.4.0.1' with respect to project 'fbtest', targeting '.NETFramework,Version=v4.7.2'
Attempting to resolve dependencies for package 'FirebaseDatabase.net.4.0.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'FirebaseDatabase.net.4.0.1'
Resolved actions to install package 'FirebaseDatabase.net.4.0.1'
Install failed. Rolling back...
Package 'FirebaseDatabase.net.4.0.1' does not exist in project 'fbtest'
Package 'FirebaseDatabase.net.4.0.1' does not exist in folder 'C:\Users\User\documents\visual studio 2015\Projects\fbtest\packages'
Install-Package : Could not install package 'FirebaseDatabase.net 4.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.
7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package auth
or.
At line:1 char:1
+ Install-Package FirebaseDatabase.net
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by bezysoftware** [comment]
I just  tried to install it in VS built-in package manager (not powershell) and it works in 4.6.1:

```
Attempting to gather dependency information for package 'FirebaseDatabase.net.4.0.1' with respect to project 'ConsoleApp1', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 22,69 sec
Attempting to resolve dependencies for package 'FirebaseDatabase.net.4.0.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'FirebaseDatabase.net.4.0.1'
Resolved actions to install package 'FirebaseDatabase.net.4.0.1'
  GET https://api.nuget.org/v3-flatcontainer/firebasedatabase.net/4.0.1/firebasedatabase.net.4.0.1.nupkg
  GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/11.0.2/newtonsoft.json.11.0.2.nupkg
  OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/11.0.2/newtonsoft.json.11.0.2.nupkg 40ms
Adding package 'LiteDB.4.1.4' to folder 'C:\Users\bezysoftware\source\repos\ConsoleApp1\packages'
Installing Newtonsoft.Json 11.0.2.
Added package 'LiteDB.4.1.4' to folder 'C:\Users\bezysoftware\source\repos\ConsoleApp1\packages'
  OK https://api.nuget.org/v3-flatcontainer/firebasedatabase.net/4.0.1/firebasedatabase.net.4.0.1.nupkg 609ms
Installing FirebaseDatabase.net 4.0.1.
Added package 'LiteDB.4.1.4' to 'packages.config'
Successfully installed 'LiteDB 4.1.4' to ConsoleApp1
Adding package 'Newtonsoft.Json.11.0.2' to folder 'C:\Users\bezysoftware\source\repos\ConsoleApp1\packages'
Added package 'Newtonsoft.Json.11.0.2' to folder 'C:\Users\bezysoftware\source\repos\ConsoleApp1\packages'
Added package 'Newtonsoft.Json.11.0.2' to 'packages.config'
Successfully installed 'Newtonsoft.Json 11.0.2' to ConsoleApp1
Adding package 'System.Reactive.4.0.0' to folder 'C:\Users\bezysoftware\source\repos\ConsoleApp1\packages'
Added package 'System.Reactive.4.0.0' to folder 'C:\Users\bezysoftware\source\repos\ConsoleApp1\packages'
Added package 'System.Reactive.4.0.0' to 'packages.config'
Successfully installed 'System.Reactive 4.0.0' to ConsoleApp1
Adding package 'FirebaseDatabase.net.4.0.1' to folder 'C:\Users\bezysoftware\source\repos\ConsoleApp1\packages'
Added package 'FirebaseDatabase.net.4.0.1' to folder 'C:\Users\bezysoftware\source\repos\ConsoleApp1\packages'
Added package 'FirebaseDatabase.net.4.0.1' to 'packages.config'
Successfully installed 'FirebaseDatabase.net 4.0.1' to ConsoleApp1
Executing nuget actions took 6,13 sec
Time Elapsed: 00:00:30.0374623
========== Finished ==========
```

Not sure how the PS1 version differs from the VS nuget manager, I never used the powershell version

**Comment by fabricciotc** [comment]
You have to change de Net framework of your project in settings...

**Comment by lucazin** [comment]
Hi ..i have  net frameowrk 4.6.1 and not working man.

PM> Install-Package FirebaseDatabase.net -pre
Installing 'FirebaseDatabase.net 4.0.4'.
Successfully installed 'FirebaseDatabase.net 4.0.4'.
Adding 'FirebaseDatabase.net 4.0.4' to Inspinia_MVC5.
Uninstalling 'FirebaseDatabase.net 4.0.4'.
Successfully uninstalled 'FirebaseDatabase.net 4.0.4'.
Install failed. Rolling back...
Install-Package : Could not install package 'FirebaseDatabase.net 4.0.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly 
references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package FirebaseDatabase.net -pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
