### ISSUE TITLE
REALTIME STREAMING INTO A LABEL

### ISSUE THREAD

**Issue by fabricciotc** [step-up-labs/firebase-database-dotnet#195]
Hi, I am develop a app in WPF using this library. First i try to update a label.content when my database change. I try to use this

using Firebase.Database;
using Firebase.Database.Query;
...
var firebase = new FirebaseClient("https://dinosaur-facts.firebaseio.com/");
var observable = firebase
.Child("dinosaurs")
.AsObservable()
.Subscribe(d => LABEL.Content(d.Key));

I think that the content of my label going yo change but doesn´t work. I want that when i add a new dinosaurs in my database see the new Key in the label.  Thanks

**Comment by bezysoftware** [comment]
Can you share a minimal reproducible example project?
