### ISSUE TITLE
corrupted offline database

### ISSUE THREAD

**Issue by kevinwong15** [step-up-labs/firebase-database-dotnet#196]
Is there a way to delete the offline database and re-start?

The offline database got corrupted for some reason when it was streaming, and everytime I tried to load it using

`                messagesDb = App.FirebaseClient.Child("Messages").Child(Connection.EngagementId)
                    .AsRealtimeDatabase<Message>(Connection.EngagementId, "", StreamingOptions.LatestOnly, InitialPullStrategy.None, true);
`

I get the following error "System.Collections.Generic.KeyNotFoundException: The given key '7' was not present in the dictionary."

I simply want a way to restart the process again..

**Comment by bezysoftware** [comment]
the `RealtimeDatabase` has a `Database` property which has a `Clear` method

**Comment by kevinwong15** [comment]
Thanks
