### ISSUE TITLE
Realtime streaming - property

### ISSUE THREAD

**Issue by hgfilho** [step-up-labs/firebase-database-dotnet#197]
Hello!
I need to verify when the status of a property change for a specific item. Is it possible?
Something like this:

using Firebase.Database;
using Firebase.Database.Query;
...
var firebase = new FirebaseClient("https://dinosaur-facts.firebaseio.com/");
var observable = firebase
  .Child("dinosaurs")
  .Child("t-rex")
  .Child("size")
  .AsObservable<string>()
  .Subscribe(d => Console.WriteLine("new size = " + d.object));

**Comment by bezysoftware** [comment]
It should be possible, what issue are you facing?
