### ISSUE TITLE
Duplicate data using Realtime Streaming

### ISSUE THREAD

**Issue by andreasnaslund** [step-up-labs/firebase-database-dotnet#198]
Awesome work @bezysoftware 

I'm trying to feed a simple ItemsControl list with real time data using AsObservible.
It's updating correctly when changing data in Firebase but all objects in my collection is duplicating randomly over time. 

**First all objects loads but after like 30 seconds the same objects adds to the list.**

Is this the wrong approach or am I missing something?

```
public MainWindow()
{
InitializeComponent();
var childUsers = client.Child("Users");
var observable = childUsers.AsObservable<User>();
Users.ItemsSource = observable.ObserveOnDispatcher().AsObservableCollection();
}
```

Cheers!

**Comment by bezysoftware** [comment]
I am not sure what the `AsObservableCollection` extension method does, but I would assume that's what causes the duplication. Essentially you can receive the same `User` object multiple times when you subscribe (it can change on server, connection can be restarted etc). In that case you need to manually handle the object being received again - either replacing the old one, or updating it.

**Comment by fabricciotc** [comment]
Just use Clear() in ur datagrid before you add a new item o modify
