### ISSUE TITLE
Xamarin sample offline/online

### ISSUE THREAD

**Issue by rvanrosmalen** [step-up-labs/firebase-database-dotnet#199]
Trying to get the sample working.
I have a database and the url configured. For the api key I use the web api key of the project (is this correct?).

The sample app just hangs forever on:
 var items = await App.DataStoreContainer.PostStore.GetItemsAsync(true);
in ExecuteLoadItemsCommand

I would have expected a timeout and exception but nothing yet. What can be wrong here?

**Comment by bezysoftware** [comment]
I have the same issue now - it just hangs there. The sample was introduced by a PR, so it must have worked at some point. I will take a look when I have time

**Comment by cabauman** [comment]
Indeed, it did work before. I'm the one who contributed the sample, but haven't touched this library or that sample in quite a while. If Bezy doesn't beat me to it I'll take a look as well, when I get some time.

**Comment by cabauman** [comment]
I just tried it as is _and_ after upgrading all the nuget packages, but am not experiencing the issue you guys are. It works fine for me, so I'm not sure I can be any help right now. Sorry.

**Comment by cabauman** [comment]
Can one of you confirm that it only hangs when there's no network connection? If so, I'll make a fix.

**Comment by bezysoftware** [comment]
I just tested in an emulator, it doesn't seem to freeze anymore even when offline. I will play with it a bit more tomorrow, perhaps udpate xamarin packages to latest

**Comment by cabauman** [comment]
Okay, cool. I'll probably make a PR to compliment that, unless you want to do it. Mainly adding Xamarin.Essentials Connectivity so we can do something like

```
if ((cacheEmpty || forceRefresh) && Connectivity.NetworkAccess == NetworkAccess.Internet)
{
    db.PullAsync();
}
```

The current code isn't using the forceRefresh parameter at all.
