### ISSUE TITLE
EqualTo(true)

### ISSUE THREAD

**Issue by bobbd** [step-up-labs/firebase-database-dotnet#20]
How can I use EqualTo to query a boolean property.
EqualTo() only accepts a bool or a double. But I'm trying to do something like this:

var appointments = await client
             .Child("appointments")
             .OrderBy("isBooked")
             .EqualTo(true)
             .OnceAsync<Appointment>();

**Comment by bezysoftware** [comment]
You're right, Boolean is currently not supported.
