### ISSUE TITLE
¿Auth database with token application?

### ISSUE THREAD

**Issue by fabricciotc** [step-up-labs/firebase-database-dotnet#200]
Hi, i would like to say if i can connect my project with my database base on firebase without write my personal key in the project and generate a token just for my project

**Comment by jaybowman** [comment]
You can create a firebase client using your server api key from firebase and not use a user/password.

 _client = new FirebaseClient(_basePath,
                new FirebaseOptions()
                {                   
                     AuthTokenAsyncFactory = () =>  Task.FromResult(firebaseServerKey)
                });
