### ISSUE TITLE
Disable random key generated in child node

### ISSUE THREAD

**Issue by Nullstr1ng** [step-up-labs/firebase-database-dotnet#202]
Sorry, not sure where to put my questions since this is github, but how do you disable the randomized key being inserted as a child? like this one here
![image](https://user-images.githubusercontent.com/260633/63647002-dca94200-c74d-11e9-8764-ffa2118d1511.png)
I have already set the *generateKeyOffline* to false or is that the correct way to disable it? How do you disable this? I am already setting custom key using GUID

**Comment by bezysoftware** [comment]
You need to `Put` instead of `Post` (Post always inserts a key)

**Comment by Nullstr1ng** [comment]
got it! Thanks!
