### ISSUE TITLE
How to use the feature OnChildAdded

### ISSUE THREAD

**Issue by apy534** [step-up-labs/firebase-database-dotnet#203]
I'm trying to subscribe only if new child is added under a node. 
**OnChildAded**
How to implement it??

Thanks in advance.

**Comment by bezysoftware** [comment]
This is implemented using and Observable, which you can subscribe to. See samples 
https://github.com/step-up-labs/firebase-database-dotnet/blob/master/samples/ConsoleChat/ConsoleChat/Program.cs
