### ISSUE TITLE
vb.net version some code sample

### ISSUE THREAD

**Issue by untipo73** [step-up-labs/firebase-database-dotnet#204]
first thanks for your wonderful work. I have searched a lot on the internet but I have not found anything that can help to understand how to use your creatures to all those who use vb.net and not C #. Would anyone be able and could help us?
Thanks again.

**Comment by bezysoftware** [comment]
I'm not experienced with vb.net at all, but if you take it upon yourself to prepare a sample, feel free to send a PR
