### ISSUE TITLE
Subscribed observable auto refresh even if there is no update after 1min30 - 1min40

### ISSUE THREAD

**Issue by leepsi** [step-up-labs/firebase-database-dotnet#205]
Hey, i'm using this package and having trouble with a subscribed observable :
After about 1min40, the listener detects an update in firebase even if there wasn't.
Here is how I create it :
```
var observableQuestions = questionListener.AsObservable<object>();
var subscriptionQuestions = observableQuestions.Subscribe(node =>
{ [...] });
```
It works but when the firebase stays inactive, then the refresh appends and breaks everything...
Is there a way to disable the auto refresh when inactive ?

Thanks for the great package anyway

**Comment by bezysoftware** [comment]
Can you shre a minimal reproducible example solution?

**Comment by leepsi** [comment]
Like any listener I'm creating does that. Here is a short exemple (without the base/token infos) :
`public static class Firesharp
    {
        private static FirebaseClient firebaseClient;

        static String rootUri = [base_url];

        public static String authToken = [token];

        public static String node = [targeted_node];

        private static ChildQuery BasicListener { get; set; }

        public static void initFirebase()
        {
            firebaseClient = new FirebaseClient(rootUri, new FirebaseOptions
            {
                AuthTokenAsyncFactory = () => Task.FromResult(authToken)
            });
            BasicListener = firebaseClient.Child(node);
            Run().Wait();
        }

        private static async Task Run()
        {
            var obseravbleItem = BasicListener.AsObservable<object>();

            var BasicSubscription = obseravbleItem.Subscribe(res =>
            {
                    Console.WriteLine("Trigged");
            });
        }
    }`

Output is (not modified) :
`Trigged
Trigged
The thread 0x2a7c has exited with code 0 (0x0).
The thread 0xf50 has exited with code 0 (0x0).
The thread 0x4c6c has exited with code 0 (0x0).
The thread 0x32e4 has exited with code 0 (0x0).
The thread 0x5158 has exited with code 0 (0x0).
The thread 0x714 has exited with code 0 (0x0).
Trigged`

I'm 100% sure that my base doesn't update anything, i watched it when I was running the test.

Thanks for the answer :)

**Comment by DevelopmentOpenworld** [comment]
This is because HttpClient disconnects due to the default timeout.
To fix this, it is necessary in the firebase-database-dotnet /src/Firebase/Streaming/FirebaseSubscription.cs file to either hard-write the timeout for the client in the constructor :)))), or pass it there (FirebaseSubscription) as a parameter.
By adding, respectively, this parameter to the public AsObservable <T> method. In the file firebase-database-dotnet / src / Firebase / Query / FirebaseQuery.cs
