### ISSUE TITLE
Cannot deserialize the current JSON array

### ISSUE THREAD

**Issue by gnout** [step-up-labs/firebase-database-dotnet#21]
I'm getting the following error:
Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.Dictionary`2[System.String,Empty.Module.Controllers.Demp]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.

when I'm running
            var sample = await firebase
                .Child("first")
                .WithAuth(auth.FirebaseToken)
                .OnceAsync<Demp>();

How can I correct the error?
Thanks

**Comment by bezysoftware** [comment]
Can you post you full data structure and what path are you trying to get / what the Demp class is? Arrays should generally not be used in Firebase as per their documentation https://firebase.googleblog.com/2014/04/best-practices-arrays-in-firebase.html

**Comment by gnout** [comment]
Thanks. It seems that the structure of the data was the problem (although I had many problem when I tried to import them in Firebase console without including them in an array.)
