### ISSUE TITLE
Subscriptions takes too long to respond to changes on UWP

### ISSUE THREAD

**Issue by Rothanan** [step-up-labs/firebase-database-dotnet#210]
I have a problem with subscriptions:

On Android it responds to changes on the database almost instantly, but when I run it on Windows 10(UWP) it takes from 3 seconds to 30 seconds to respond to changes.

Anyone having this issue?

(I will post a sample code as soon as I can)

**Comment by bezysoftware** [comment]
It's due to the nature of the C# implementation - it uses HTTP event stream, while Android uses websockets. It also depends on what you observe - if you observe a large node, everything needs to fetched first before streaming starts
