### ISSUE TITLE
Deleting child throws an error

### ISSUE THREAD

**Issue by adsonvinicius** [step-up-labs/firebase-database-dotnet#214]
I have a simple structure: 
_ROOT_
- users
   - Token
   - UserName

So I tried to delete a node by its value (Token) but raises an error

**_await firebase.Child("users").OrderBy("Token").EqualTo("TOKEN_VALUE").DeleteAsync();_**

"error": "Exception occured while processing the request.\nUrl: https://myproject.firebaseio.com/users/.json?orderBy=\"Token\"&equalTo=\"TOKEN_VALUE\"&auth=AUTH_KEY\nRequest Data: \nResponse: {\n  \"error\" : \"Unsupported operation\"\n}\n"
}

When I paste this URL on browser the item I want to delete is shown. However I can't delete it.

By the way _**await firebase.Child("users").DeleteAsync();**_ works fine.

**Comment by bezysoftware** [comment]
As the error says, this isn't supported by firebase. You need to get the keys first and then delete one by one
