### ISSUE TITLE
Service unavailable randomly (error 503)

### ISSUE THREAD

**Issue by GrEg00z** [step-up-labs/firebase-database-dotnet#216]
Hello,

I'm using FirebaseDatabase.net inside a custom job developped in .Net Core, to save my data in my realtime database, like this :

```
var TaskPut = this._firebaseClient
          .Child($"{SyncServiceTools.ISynchronisableObjectName(Object)}/{Object.Id}")
          .PutAsync(Object);

TaskPut.Wait();
```

99% of the time, everything works as expected, data are correctly saved on firebase. 
Also, my custom job performs a retry on the saving method : if any error detected, we retry 2 times the save (by waiting 500ms, and 1s during each retry)

But sometimes, maybe one time every 2 months, I got this error when saving a data to firebase :

Response: {
   "error" : "Firebase database instance is inactive"
}
---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).
    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
    at Firebase.Database.Query.FirebaseQuery.<SendAsync>d__18`1.MoveNext()
    --- End of inner exception stack trace ---
    at Firebase.Database.Query.FirebaseQuery.<SendAsync>d__18`1.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Firebase.Database.Query.FirebaseQuery.<PutAsync>d__12`1.MoveNext()

Do you have any informations about this problem ? It would help us a lot !

Thanks by advance

**Comment by bezysoftware** [comment]
I can only guess it's an issue with google's servers, 503 error comes from their backends. They have it documented here, although nothing useful.. https://firebase.google.com/docs/reference/rest/database
