### ISSUE TITLE
Query nested object

### ISSUE THREAD

**Issue by MihelUta** [step-up-labs/firebase-database-dotnet#217]
can query to get the nested object? its posible? this database scheme.
`
 "-Lt9Fxz1uz_z49qMEWuO" : {
            "Group_Name" : "A",
            "List" : {
              "-Lr8_i-JOc00iNqVS-ie" : {
                "Name" : "a",
              },
              "-Lt7valaixRDEN2fKnf5" : {
                "Name" : "b",
              }
            }
`

**Comment by bezysoftware** [comment]
If you mean query a collection inside other collection, then no, that isn't possible

**Comment by MihelUta** [comment]
ok thankyou for your answer.
