### ISSUE TITLE
cannot install on rider jetbrains with mac os catalina

### ISSUE THREAD

**Issue by vadev** [step-up-labs/firebase-database-dotnet#218]
I install by using nuget and not installing properly when doing `using Firebase.Database.Query`
I am using .Net Core with 3.0.101 version with mono framework. 

Thank you.

**Comment by bezysoftware** [comment]
So does it or doesn't it install to your project? What is the error?

**Comment by vadev** [comment]
it does not install. It installs and then few minutes later it uninstalls. Do you have a compatible documentation how to install it properly?

**Comment by bezysoftware** [comment]
I don't have any documentation, I just normally install it from visual studio nuget package manager and that's all.

**Comment by vadev** [comment]
Any tips what to do in order to fix these issue?

**Comment by vadev** [comment]
and with what .net core version do you have and  what mac os are you on? maybe the newer mac os does not support? hmm..

**Comment by vadev** [comment]
Do you have a .dll? Or can I install it manually instead of nuget?

**Comment by vadev** [comment]
Also when installing  via nuget:  First, I get a error on: `using Firebase.Database.Query;` that says "namespace name expected; "Firebase.Database.Query. is a type not a namespace"

**Comment by vadev** [comment]
It says v.4.0.4 was successfully installs to Assembly-CSharp. But when I use the Firebase.Database.Query it gives me an error: `A 'using namespace' directive can only be applied to namespaces; 'Query' is a type not a namespace. Consider a 'using static' directive instead`

**Comment by vadev** [comment]
Okay. I am using Unity with it - does  .net framework support  FirebaseDatabase.NET ?
