### ISSUE TITLE
Post with Authentication Results in Error 400 (Bad Request)

### ISSUE THREAD

**Issue by PreslandBoy** [step-up-labs/firebase-database-dotnet#22]
I've got some pretty simple code which should create a new ClassRoom object and save it to Firebase under "classRooms". If I change my authentication rules in the database to allow universal access and I remove the authentication part of the request, everything works fine. So I think the issue has something to do with authentication.

Here's the code which makes the request:
```
String id = subjectId.Text;
String name = subjectName.Text;
String activity = this.activity.Text;

var classRoom = await firebase
            .Child("classRooms")
            .WithAuth(auth.FirebaseToken)
            .PostAsync<ClassRoom>(new ClassRoom(id, name, activity));
```

And here's the ClassRoom class:
```
class ClassRoom
    {
        public String subjectId;
        public String subjectName;
        public String activity;

        public ClassRoom(String subjectId, String subjectName, String activity)
        {
            this.subjectId = subjectId;
            this.subjectName = subjectName;
            this.activity = activity;
        }
    }
```

Thanks so much for any time anyone puts in to this. Your efforts are much appreciated 👍

**Comment by jaybowman** [comment]
I'm doing the same thing with authentication and it is working. Have you checked your database rules? I don't have any other suggestions.

 await _client.Child("homes")
                           .WithAuth(token)
                           .PostAsync<Home>(ihome);

**Comment by jaybowman** [comment]
forgot to do the insert code so my code lost the angle brackets.
```
 await _client.Child("homes")
               .WithAuth(token)
               .PostAsync<Home>(ihome);
```

**Comment by PreslandBoy** [comment]
Well damn, my auth read and write rules are currently just the simple "auth != null". I'm out of ideas too :(

**Comment by jaybowman** [comment]
My mistake, I'm having the same problem. 400 bad request, My update is working with the PutAsync() with authentication but the post isn't 
```
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Firebase.Database.Query.FirebaseQuery.<SendAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Firebase.Database.Query.FirebaseQuery.<PutAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Firebase.Database.Query.FirebaseQuery.<PostAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at FirebaseSandbox.Services.FirebaseService.<UpdateDatabase>d__7.MoveNext() in D:\Projects\FirebaseSandbox\Services\FirebaseService.cs:line 92
```

**Comment by jaybowman** [comment]
I'm adding the source project to my solution to try to debug the problem. Looks like it is in the FirebaseQuery.SendAsync method.

**Comment by jaybowman** [comment]
After testing, in the firebaseQuery.SendAsync line 240
` responseData = await result.Content.ReadAsStringAsync().ConfigureAwait(false);`
responseData has:
{
  "error" : "Could not parse auth token."
}

**Comment by jaybowman** [comment]
I noticed on the postAsync() there was a /.json at the end of the auth= string. Where on the putAsync() there was just the auth string. I remove the /.json in debug and then I received this error
"error" : "Unable to validate signature."

**Comment by luccasclezar** [comment]
I'm having the same issue, and searching for ".json" in the repository returns only a single string that is not in the middle of some other string. It's in the ChildQuery file in line 67 (https://github.com/step-up-labs/firebase-database-dotnet/blob/f4be3b7e34ae327653a9b4a8540db5b18c78b938/src/Firebase/Query/ChildQuery.cs). I think this is the place where the error is coming from.

**Comment by jaybowman** [comment]
I think I see what is happening but I don't know where to fix it yet.  On the insert of a new object "PostAsync() a Pkey is generated and then a new child query is created with the new key. When the URL is being built the child query is ending up at the end of the url after the auth query parameter. 
Instead of like this.
```
 https://the-my-app.firebaseio.com/homes/-KVQB_j5emmwtmceoWC_/.json?auth=eyJhbGc...
we get.
https://the-my-app.firebaseio.com/homes/.json?auth=eyJhbGci...-KVVbs-c8h2ZwccEZM87/.json
```

**Comment by jaybowman** [comment]
Here is a workaround, generate the key outside the postAsyn() or at this point you can call  putAsync()
   ```
string key = Firebase.Database.FirebaseKeyGenerator.Next();
   // insert this works, creates a correctly formated URL
   await _client.Child("homes")
                       .Child(key)
                       .WithAuth(token)                              
                       .PostAsync<Home>(myhome, false);
```

**Comment by PreslandBoy** [comment]
For the workaround you need to do PutAsync. But yes that does work for now, thanks  :D

**Comment by bezysoftware** [comment]
Hi folks, sorry for taking so long to reply, I was on vacation. Anyway, the solution mentioned by @jaybowman will work, however that's not the preferred way of doing it. I will actually obsolete the "WithAuth" method and remove it later completely. 

The preferred way of doing auth is using the `FirebaseClient`'s constructor with `FirebaseOptions` like this:

```
            var firebaseClient = new FirebaseClient(
                "<URL>",
                new FirebaseOptions
                {
                    AuthTokenAsyncFactory = () => Task.FromResult("...") // can also be async call
                });
```

I will amend the docs for auth to reflect this.

**Comment by steveharan** [comment]
Complains about:

 new FirebaseOptions

FirebaseOptions does not exist

**Comment by steveharan** [comment]
"For the workaround you need to do PutAsync"

```
            var result = await firebase
              .Child("104837")
              .WithAuth(auth.FirebaseToken)
              .PutAsync(new { newMessage = true });
```

this always gives me the compile error:

Cannot assign void to an implicitly typed variable

**Comment by steveharan** [comment]
Figured it's much easier to use a combination of firebaseauth to get the auth token, and then just use RestSharp like so:

```
            var ownerId = 123456;
            var client = new RestClient(String.Format("https://ownerportal-61402.firebaseio.com/{0}.json?auth={1}", ownerId, auth.FirebaseToken));
            var request = new RestRequest("", Method.PUT);
            request.RequestFormat = DataFormat.Json;
            request.AddBody(new { newMessage = false});
            IRestResponse response = client.Execute(request);
            Console.Write(response.StatusCode.ToString());
```

**Comment by bezysoftware** [comment]
FirebaseOptions are available in latest 2.x releases, they have been in alpha until now, 2.0.1 is publicly available.
