### ISSUE TITLE
subscribe is not working realtime

### ISSUE THREAD

**Issue by kmhk** [step-up-labs/firebase-database-dotnet#220]
fbAuth = await authProvider.SignInWithEmailAndPasswordAsync(email, pwd);

fbClient = new FirebaseClient(firebaseURL, options: new FirebaseOptions {
                    AuthTokenAsyncFactory = () => Task.FromResult(fbAuth.FirebaseToken)
});

var observable = fbClient.Child("alarm").AsObservable<FirebaseDataAlarm>();
var subscription = observable.Subscribe(data => Console.WriteLine($"note: {data.Key}"));

This is not working correctly when the db is changed.
How can I fix this code?

**Comment by lucazin** [comment]
same here  not  fired when i change update or insert a new item

**Comment by lucazin** [comment]
didi u find some solution man?
