### ISSUE TITLE
Datatbase secretes have been depreciated

### ISSUE THREAD

**Issue by LindaLawton** [step-up-labs/firebase-database-dotnet#221]
Datatbase secretes have been depreciated do you have a way of doing this using Firebase Admin sdk?

![image](https://user-images.githubusercontent.com/6592543/72514776-391d1300-384f-11ea-9bcf-b9aa6914497c.png)

```
var auth = "ABCDE"; // your app secret
var firebaseClient = new FirebaseClient(
  "<URL>",
  new FirebaseOptions
  {
    AuthTokenAsyncFactory = () => Task.FromResult(auth) 
  });

```

**Comment by tanwarsatya** [comment]
Yes this need to be addressed, any help will be appreciated.

**Comment by LindaLawton** [comment]
I think I got this working I just need to find the code and I can update this

**Comment by tanwarsatya** [comment]
You can fork and submit a PR. How did you got it working did you modify the code ?

**Comment by LindaLawton** [comment]
I used the Google api .net client library service account auth code to login to the admin API

**Comment by proyoli** [comment]
Any news regarding this matter?
@LindaLawton can you please elaborate on how you used the Google api .net client library?
Thanks.

**Comment by LindaLawton** [comment]
Login using a service account with the Admin sdk api.

**Comment by wikes82** [comment]
for anyone needing sample code to use service account file
`var firebaseClient = new FirebaseClient(FirebaseUrl, new FirebaseOptions
                {
                    AuthTokenAsyncFactory = () => GetAccessToken(),
                    AsAccessToken = true
                });`

GetAccessToken() is something like this :
`private async Task<string> GetAccessToken()`
`        {      `      
`            var credential = GoogleCredential.FromFile(pathToJsonFile).CreateScoped(new string[] {`
`                "https://www.googleapis.com/auth/firebase.database",`
`                "https://www.googleapis.com/auth/userinfo.email" });`

`            ITokenAccess c = credential as ITokenAccess;`
`            return await c.GetAccessTokenForRequestAsync();`

`        }`

**Comment by JasperTack** [comment]
The sample code from wikes82 worked for me when I added the second scope:
```
// Define the required scopes.
var scopes = [
  "https://www.googleapis.com/auth/userinfo.email",
  "https://www.googleapis.com/auth/firebase.database"
];
```
As described here: https://firebase.google.com/docs/database/rest/auth

**Comment by monodop** [comment]
Would love to see this documented on the readme

**Comment by bezysoftware** [comment]
Linked from readme
