### ISSUE TITLE
Correct deserialization enum

### ISSUE THREAD

**Issue by DevelopmentOpenworld** [step-up-labs/firebase-database-dotnet#222]
In FirebaseCache.cs method:
`public IEnumerable<FirebaseObject<T>> PushData(string path, string data, bool removeEmptyEntries = true)` 

code:
`if ((valueType.GetTypeInfo().IsPrimitive || valueType == typeof(string) ||        typeof(IEnumerable).IsAssignableFrom(valueType)) && primitiveObjSetter != null)`

must be replaced with this:
```
if ((valueType.GetTypeInfo().IsPrimitive || valueType == typeof(string) || typeof(IEnumerable).IsAssignableFrom(valueType)) && primitiveObjSetter != null || valueType.BaseType == typeof(Enum))
```

**Comment by bezysoftware** [comment]
Feel free to open a PR
