### ISSUE TITLE
RealTime Streaming not working.

### ISSUE THREAD

**Issue by lucazin** [step-up-labs/firebase-database-dotnet#227]
Hi my friend how are u?
Thanks for this lib!

The real streaming whe data changes not working my friend, i add new data and the observable not fire.. the node only have 2 items..so its not bigger.

Just when i remove all data is fired on event InsertUpdated.. but im deleting.

`var child = firebaseClient.Child("ESTABID_17").Child("PEDIDOS_DELIVERY");
            var observable = child.AsObservable<delivery>();

            var subscription = observable.Subscribe(

                d =>
                {
                    if (d.EventType == Firebase.Database.Streaming.FirebaseEventType.InsertOrUpdate)
                    {
                        insert(d.Object);
                    }
                    else if (d.EventType == Firebase.Database.Streaming.FirebaseEventType.Delete)
                    {
                        delete(d.Object);
                    }
                    else
                    {
                        delete(d.Object);
                    }
                }
           );`

can u help me my friend?

**Comment by lucazin** [comment]
Can someone help me with this?

**Comment by cabauman** [comment]
What if you do `AsObservable<YourType>()`?

**Comment by lucazin** [comment]
It's working man..
But I don't know why the event I fired 2x times..

I can't figure out and discover the difference of update event and insert event.. Because it's the same condition.. Don't have a separation event in if condition just insert update together. How can fix this?
