### ISSUE TITLE
Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.List`1[Object]]'

### ISSUE THREAD

**Issue by francisco-dechoudens** [step-up-labs/firebase-database-dotnet#228]
when executing DBClient.client.Child("Blogs").OnceAsync<Blog>()).

I get : 
Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.List`1[ibMobile.Entities.Blog]]'

Is getting from DB:
[{"Author":"PIBH","AverageReadingTime":"1 min read","BlogId":"1","CreateOn":"2020-01-01T10:00:00","Date":"Apr 01","Description":"","ImagePath":"https://www.solg.org/wp-content/uploads/2017/11/Abraham-1024x768.jpg","Name":"Sacrificio Vivo"},{"Author":"Pastor Omar Santiago","AverageReadingTime":"2 mins read","BlogId":3,"CreateOn":"0001-01-01T00:00:00","Date":"Apr 02","Description":"Estamos en un tiempo donde las emociones y sentimientos afloran de forma fácil. La sociedad reacciona ante los diversos eventos de una forma volátil e  inestable. Se anuncia cualquier evento atmosférico y salimos despavoridos a  comprar provisiones; existe cualquier tipo de enfermedad en el ambiente y  deseamos comprar los medicamentos para tenerlos por si hace falta. Me parece, amados hermanos y hermanas, que debemos ser sabios y entendidos  ante la realidad de vida que tenemos. Hoy, nuestro Señor Jesucristo sigue  siendo el Señor de la Vida. Me parece que en \t ocasiones nos encontramos alarmados y ansiosos por cosas que genuinamente no podemos controlar.  Analizando todas estas cosas, deseo que miremos este verso con una mirada  nueva. El Apóstol le está diciendo a los creyentes de Tesalónica, que no  debemos per der de perspectiva la vida espiritual. Este verso nos invita a mantenernos vigilantes y activos en el propósito y voluntad de Dios. Hoy hay    muchas seducciones o pensamientos que van poco a poco deslizándonos de lo que Dios desea para nuestra vida, para nuestra familia y comunidad de fe. No dejes que los cantos de sirena de este mundo te roben el poder escuchar  la voz de Dios. Debemos velar, debemos mantener nuestra lámpara     encendida y manteniendo la mirada puesta a Cristo.  ¡Debemos ser sobrios! ¿A que se refiere la biblia a ser sobrio? La palabra  “Nepho” o sobrio quiere decir conseguir el autocontrol recuperar la  sobriedad, contener la influencia controladora de emociones o deseos    excesivos (y por lo tanto que lleguen a ser razonables); concebido como recuperar la sobriedad de la influencia del alcohol. Es tener dominio propio,  poder controlar nuestra vida, nuestras decisiones, nuestros pensamientos.  Amada Iglesia, hoy debemos permitir que Dios sea quien dirija nuestras    emociones y sentimientos. No debemos actuar bajo el coraje, la influencia de los medios de comunicación u otras personas. Nada debe dominar nuestras  emociones y decisiones sino solo Cristo. En un mundo donde hay tanto  engaño y falsedad, debemos depositar nuestra vida en los brazos amorosos    de Cristo. Dejemos que el Espíritu Santo nos llene de su presencia y poder. Dejemos que Dios haga su voluntad en nuestra vida. Le aseguro que Dios  manifestará su poder y gloria de forma maravillosa.","ImagePath":"https://i0.wp.com/psicoguias.com/wp-content/uploads/2018/08/gestion-estres.png?fit=880%2C360&ssl=1","Name":"Seamos Sobrios"},{"Author":"Pastor Omar Santiago","AverageReadingTime":"2 mins read","BlogId":4,"CreateOn":"0001-01-01T00:00:00","Date":"Apr 03","Description":"Por lo tanto, mis amados hermanos, permanezcan fuertes y constantes. abajen siempre para el Señor con entusiasmo, porque ustedes saben que  \tnada de lo que hacen para el Señor es inútil.   1 Corintios 15:58 (NTV)     ¡Que glorioso es servir al Señor y trabajar en su obra! Ver las vidas salvarse, la iglesia siendo edificada y el  crecimiento de otros creyentes nos llena de gozo y satisfacción. Cuando trabajamos en la obra de Dios y podemos aportar con  nuestros talentos, dones y posesiones en la viña, somos bendecidos y Dios  recibe toda la Gloria. El Apóstol Pablo se encuentra escribiendo a la iglesia en Corintios y les hace saber varias cosas importantes sobre el trabajo en la viña  del Señor. \t  Pablo les anima a que estén fuertes (firmes o inamovibles) y constantes en la  obra. La primera expresión a los Corintios es que permanezcan fuertes, firmes, inamovibles, constantes, dando a entender que el creyente debe estar  dedicado al Señor. Ante tantos  pensamientos diversos, solo la fe en el Unigénito Hijo de Dios nos garantiza nuestra salvación y victoria. Amado y   Amada, manténgase firme en los propósitos de Dios para usted y su familia. No permita que nada le robe a usted el premio del supremo llamami \tento, Dios es nuestro amado y mayor regalo. \t  Otra cosa que nos insta el Apóstol es a trabajar con entusiasmo. La versión  Reina Valera usa la palabra “Creciendo” que viene de la palabra “perisseuo” tener en abundancia, copioso, que existe en grandes cantida  \tdes, se desborda. Esta expresión se refiere a cuando se solicita a alguien para trabajar,  aparezcan muchos voluntarios. Es cuando hay que organizar o \t limpiar, realizar un trabajo incómodo o que no tiene exposición y hay muchos dispuestos a realizarlo. Mis  amados, cuando vamos a realizar un trabajo para Dios, sabemos que Dios nos ve con agrado, pero también nosotros debemos  realizar la tarea con alegría , gozo, con ánimo y deseos de bendecir el corazón de Dios.  Finalmente, todo lo que hacemos para el Señor t \tiene un propósito en Él. La versión Reina Valera dice: “nuestro trabajo en el Señor no es en vano”.  Amada Iglesia, yo conozco el corazón de ustedes, q \tue los que trabajan lo hacen de forma humilde y sin que su nombre sea reconocido. Todos sabemos que la rec ompensa viene del Cielo y que no hay forma en como pagarle a Dios por lo mucho que nos ha dado. El trabajo que Dios te ha puesto a realizar no  quedará  sin fruto o vacío. Dios se agrada del corazón nuestro cuando adoramos y servimos de todo corazón. En este día recuerda darle lo mejor al Señor y trabajar en la viña, Dios no faltará en bendecir.","ImagePath":"https://ammiratadaniela.files.wordpress.com/2019/07/jul-24.jpg?w=484&h=484","Name":"Una Recompensa Segura"},{"Author":"Pastor Omar Santiago","AverageReadingTime":"2 mins read","BlogId":"5","CreateOn":"0001-01-01T00:00:00","Date":"Feb 02","Description":"Porque el siervo del Señor no debe ser contencioso, sino amable para con   \ttodos, apto para enseñar, sufrido… 2 Timoteo 2: 24     El Apóstol Pablo se encuentra discipulando a Timoteo, un joven pastor. Timoteo era hijo de un hombre gentil y su madre era una judía. Timoteo creció en la fe  gracias al testimonio de su madre y abuela, mujeres creyentes que se había  convertido al cristianismo. Él se encuentra pastoreando en Éfeso, una obra muy importante para Pablo y de donde surgieron otras congregaciones. Para Pablo,  Timoteo era como un hijo en la fe y deseaba darle unas herramientas para el  ministerio. En su escrito de 2 Timoteo nos hablan de ser testigo de  \tCristo, ser un buen soldado de Cristo y en esta sección la temática se refiere a ser un obrero aprobado. Pablo ofrece algunas características que debe tener el que sirve a Dios.  Me parece importante, amado y amada, que veamos varias de las palabras que  utiliza Pablo en este verso en el idioma griego para entender mejor el mensaje. La    primera palabra seria “siervo”. A tu entender ¿Qué significa siervo del Señor o Siervo? A mi viene a la mente una persona que  \testá sometida a la voluntad de Dios. La palabra s iervo en el griego “doulos” que es esclavo, sustantivo, una persona que legalmente es propiedad de otra persona y cuyo sustento entero y propósito eran determinados por su amo. Entonces, debemos estar claros que  nosotros como siervos del Señor Jesucristo,  \testamos sometidos a su voluntad y Él es nuestro sustento. Amados y amadas, al conocer que somos esclavos de Cristo por el amor que   él nos ha dado, nuestra vida es transformada. Dios desea que sus hijos seamos con Él, santos y amados. Pregunta, entendiendo  \testa palabra “siervos/esclavos” ¿Eres siervo de Cristo? ¿Sirves a Cristo como el desea ser  servido?  Una de las características establecidas en el verso, sobre el siervo de Dios, es que  no debe ser contencioso sino amable. Definamos esos términos, contenci \toso “machomai” discutir (argumentar) verbo que significa enfrentarse seriamente,   pelear, reñir, discutir (sea físicamente o verbalmente), luchar, guerrear, disputar. Esta palabra describe la actitud de una persona intransigente, que le gusta la  contienda o  la pelea, que le gusta chocar con la gente por cuestiones invaluables. Que muchas ocasiones peleamos y estamos dispuestas a vivir en contienda por cosas que verdaderamente no tienen valor. Hay hermanos que pelean por quien  era el favorito de mamá o papá,  otros por a quien le compraban los mejores regalos y viven adoloridos por cosas que no tienen valor alguno.    La otra palabra que aparece es amable “Epios” que significa gentil (tierno), adjetivo, tener o mostrar una naturaleza bondadosa o sensible. De esta palabra  sale piadoso, amable o bondadosos.   La concordancia \"Strong\" la define como afable, suave, amable o tierno.","ImagePath":"https://image.shutterstock.com/image-photo/potter-work-workshop-place-260nw-780056671.jpg","Name":"Transformados por la Palabra para la Gloria de Dios"},{"Author":"Pastor OmarSantiago","AverageReadingTime":"1 mins read","BlogId":6,"CreateOn":"0001-01-01T00:00:00","Date":"","Description":"Vestíos, pues, como escogidos de Dios, santos y amados, de entrañable misericordia, de benignidad, de humildad, de mansedumbre, de paciencia; soportándoos unos a  otros, y perdonándoos unos a otros si alguno tuviere queja contra otro. De la manera  o os perdonó, así también hacedlo vosotros. Y sobre todas estas cosas vestíos  que Crist de amor, que es el vínculo perfecto.   Colosenses 3: 12 \t-14     Desde el Edén, Dios ha establecido un plan con la humanidad. ¡Dios siempre ha estado activo en la vida del ser humano ofreciendo una vida abundante! El  pecado al entrar a la humanidad produce unos efectos devastadores. El peor  desastre que haya venido sobre la humanidad ha sido esa separación entre Dios y el hombre, el pecado. Para los creyentes, la Biblia nos revela ese plan, ofreciendo  un medio de Gracia y Salvación. Es la Palabra de Dios el instrumento utilizado  para mostrar nuestra necesidad de Dios y al mismo tiempo ofrecernos un camin o a una relación restablecida por Cristo para con el Padre.     Es la Palabra de Dios “La Biblia” la revelación especial de Dios para nosotros su  pueblo. En la vida del creyente la Biblia es vital y debe ser considerada como    alimento para su alma. Las Escrituras nos llevan al conocimiento de Dios y transforman nuestra forma de pensar. Nuestro pensamiento es transformado  cuando, sometido al Espíritu Santo, vamos al estudio de la Palabra de Dios y ella  comienza a examinar nuestros pensamientos, comportamientos e intenciones. La acción del Espíritu Santo es amonestar, redargüir, inquietar o interpelar al ser   humano. Juan 16: 8 nos dice (refiriéndose al Espíritu Santo): “Y cuando él venga,  convencerá al mundo de pecado, de justicia y de juicio”. Es la Palabra de Dios el    instrumento que el Espíritu Santo utiliza para entender el corazón de Dios y fórmanos en hijos suyos. \t     El gran reto que enfrentamos como Iglesia es ser transformados y no conforma rnos a la imagen que este mundo quiere darnos, como lo dice Romanos 12:2  (NBV) “No se amolden a la conducta de este mundo; al contrario, sean personas diferentes en cuanto a su conducta y forma de pensar. Así aprenderán    lo que Dios quiere, lo que es bueno, agradable y perfecto”. Es mi sentir en el Señor trabajar con nosotros d e forma individual (Madurez Cristiana), familias ( para la Gloria de Dios) y congregación (Fundamentos de la fe). En ocasiones deseamos trabajar tantos aspectos de la vida de la iglesia, pero si no se trabaja con el individuo; en nuestra relación personal e \t íntima con Dios, el carácter y sanidad interior, podemos estar trabajando en vano. En el ámbito de la familia  debemos ser cuidadosos en la forma en que formamos nuestra casa; Salmo 127:    1 “Si Jehová no edificare la casa… ","ImagePath":"https://gabrielgila.files.wordpress.com/2018/04/dei-verbum-708x350.jpg?w=636","Name":"Transformados por la Palabra para la Gloria de Dios"}]

Also in Firebase I have:

![image](https://user-images.githubusercontent.com/5543412/79283453-e8d14380-7e85-11ea-994b-1ff1e9ae3dcc.png)

I see that it appear as an array when getting the response. Does anyone know how to get this right, without changing the Database array to json objects?

**Comment by bezysoftware** [comment]
I would just deserialize to a dictionary, which is the default, and then transform the dictionary to array, where the keys are indexes into the array
