### ISSUE TITLE
Update single string in Node

### ISSUE THREAD

**Issue by lucazin** [step-up-labs/firebase-database-dotnet#229]
Hello!

I want to update but o have this exception.

Exception occured while processing the request.
Url: https://URL/ESTABID_17/PEDIDOS_DELIVERY/-Lzhy-dZ9iFiJ823q9sMQ/codigoPedido/.json?print=silent
Request Data: dddd
Response: {
  "error" : "Invalid data; couldn't parse JSON object, array, or value."
}

I use like this

  String xx = "dddd";
                await firebaseClient
               .Child("ESTABID_17")
               .Child("PEDIDOS_DELIVERY")
               .Child("-Lzhy-dZ9iFiJ823q9sMQ")
               .Child("codigoPedido")
               .PutAsync(xx);

Why have / after codigo pedido?

Thanks!

**Comment by bezysoftware** [comment]
For updating primitive values you need to supply a generic type to the PutAsync method - `.PutAsync<string>(xx)`

**Comment by lucazin** [comment]
Thanks Bezy!

Im facing other problem with real streaming.. 
The observables is not working e and when working the events for delete and insert not work..just update events.

**Comment by actopozipc** [comment]
Had the same problem, is it mentioned somewhere in the documentation that you need to call PutAsync<type> for basic data types?
