### ISSUE TITLE
PostAsync with pre-defined key

### ISSUE THREAD

**Issue by joanlopez** [step-up-labs/firebase-database-dotnet#23]
Hello,
Is it possible to do a PostAsync request with a manually defined key?

I want to follow the example below setting the ```auth.uid``` as the key.
https://firebase.google.com/docs/database/security/user-security

Thanks!

**Comment by bezysoftware** [comment]
Make it a `PutAsync`, to the child location of your key, e.g. `client.Child(key).PutAsync(data);`

**Comment by joanlopez** [comment]
Finally I've used an URL-based approach, but your proposal is also a good choice!

Thanks a lot!
