### ISSUE TITLE
SyncExceptionThrown is happening when I add new data

### ISSUE THREAD

**Issue by sparrow58** [step-up-labs/firebase-database-dotnet#230]
I don't know why I get this exception when I use Offline functionality. Nothing is wrong with accessing the database because data gets fetched normally.
"One or more errors occurred. (Exception occured while processing the request.\nUrl: https://moh-nonti…"

**Comment by sparrow58** [comment]
The problem was because I was referencing from the Cloned project. I just changed the reference to the nuget package and it works! 
That's weird!

**Comment by mbilalbenli** [comment]
Hi @sparrow58 , I have same issue. Can u more explain your solution?
