### ISSUE TITLE
Get Document By Id

### ISSUE THREAD

**Issue by emin-karadag** [step-up-labs/firebase-database-dotnet#233]
Hello there,
I want to shoot only one with a specific ID, not an entire document saved on Firebase Database.
How can I get a single record exclusively without capturing all records?
Thanks :)

**Comment by hieunguyen336** [comment]
Maybe this document will help you @emin-karadag 
https://firebase.googleblog.com/2013/10/queries-part-1-common-sql-queries.html#byid

**Comment by emin-karadag** [comment]
Okey thank you :)
@hieunguyen336
