### ISSUE TITLE
Observable event fired for no reason

### ISSUE THREAD

**Issue by ThibaudMZN** [step-up-labs/firebase-database-dotnet#238]
When adding a simple observable following your example, I get the subscrided event fired for the entire database's children of the node, every few minutes. The event is of source OnlineStream, and the type is InsertOrUpdate, but there's no one else updating the database and I think this i really data unefficient. Any idea why is this firing on its own and how I can fix it ?

**Comment by johncruyt** [comment]
I’m having the same problem. Indeed, very inefficient to handle the data. If someone find a solution it would be very helpfull.

**Comment by johncruyt** [comment]
Hello Thibaud, after spending lots of time I've found a solution.
You need to rebuild the Firebase.dll and replace it in your VS packages folder.
First download the firebase-database-dotnet project from github and open the project in VS.
Open the file "FirebaseSubscription.cs" and add some code like marked in yellow.
![image](https://user-images.githubusercontent.com/24864494/85015439-432d9f80-b168-11ea-8a40-26fbc46c1ba0.png)
Rebuild the solution, replace the DLL and problem solved!
Hopefully it helped you.

**Comment by ThibaudMZN** [comment]
Hi John !
Thanks for the fix, what is that Timeout doing exactly ? I'll make sure to rebuild the project thent !

**Comment by ThibaudMZN** [comment]
If this actually work maybe you should do a Pull Request on this repository !

**Comment by johncruyt** [comment]
Hello Thibaud,
Without setting the Timeout value, the HttpClient disconnects on the default timeout.
The trick is to set the value to Infinite.
I'm testing my project since this morning and it works perfectly!
I'm curious on your progress...Bon Chance! :)
