### ISSUE TITLE
Issue deserializing boolean value

### ISSUE THREAD

**Issue by kingsurf** [step-up-labs/firebase-database-dotnet#24]
In file FirebaseSubscription line 176 

`var data = result["data"].ToString();`

If the data is a boolean in firebase the value of result["data"] is {True} and the string representation is "True".  It will then fail in file FirebaseCache.cs at line 131 when attempting to deserialize "True" to a boolean value

`
                var targetObject = valueType == typeof(string) ? data.ToString() : JsonConvert.DeserializeObject(data, valueType);`

**Comment by bezysoftware** [comment]
Can you post what your data looks like, how you are subscribing and what value you're triggering to cause this?
