### ISSUE TITLE
How can I use the SetAsync method?

### ISSUE THREAD

**Issue by hieunguyen336** [step-up-labs/firebase-database-dotnet#240]
Currently, I use the PostAsync() to push the object to Firebase and the response will return the generated key and the object. However, I would like to control the generated key, as UUID. I know the method **set()** in Firebase but there is no set method in the lib right now?

**Comment by TheGocc** [comment]
Hey, I just ran into the same problem yesterday, and I found out, that if you use dictionary, (with using UUID for the dictionary's key), with put it generates and entry in the realtime database, with ID -> UUID.

`                Dictionary<string, DbData> tmp = new Dictionary<string, DbData>();
                DbData userData = new DbData
                {
                    Admin = false,
                    Name = "Mr. QWE"
                };
                tmp.Add(data.User.LocalId, userData);
                await db.Child("users").Child(data.User.LocalId).PutAsync(userData);`

If you have another UUID it will create another child in users

**Comment by hieunguyen336** [comment]
@TheGocc 
It's great. Thank for your support
