### ISSUE TITLE
Feature Request: array-contains-any & IN queries

### ISSUE THREAD

**Issue by Fenki404** [step-up-labs/firebase-database-dotnet#244]
As in the link described there is a support for queries IN, and array-contains-any.
did you think about to support these features?

https://medium.com/techwasti/firestore-now-supports-in-queries-array-contains-956031f753d4

**Comment by bezysoftware** [comment]
Unless it's supported by the REST api it cannot be added - https://firebase.google.com/docs/database/rest/retrieve-data
