### ISSUE TITLE
How can I order by child

### ISSUE THREAD

**Issue by rbryanben** [step-up-labs/firebase-database-dotnet#256]
I have a RTD structure like this

```
chatsock-913ax
       |_ _Accounts
               |__ rbryanben
                        |___email:  "rbryanben@gmail.com"
                        |___id:  "rbryanben"
                        |___key:  "Yrg2HAdvcGH3j5hBHODEN356njwkJHDb932b"
                        |___password: "demdkml"
```

I want to get the data of rbryanben , but using a criteria of email "rbryanben@gmail.com"

I have tried this query, and its not working

```
var emailQuery = await firebase
                        .Child("Accounts")
                        .OrderBy("email")
                        .EqualTo("rbryanben@gmail.com")
                        .OnceAsync<Account>();
```

**Comment by cabauman** [comment]
Did you apply indexing to your email key?

> Add Indexing to your Firebase Realtime Database Rules: If you're using orderBy in your app, you need to define the keys you will be indexing on via the .indexOn rule in your Firebase Realtime Database Rules. Read the documentation on the .indexOn rule for more information.

Source: https://firebase.google.com/docs/database/rest/retrieve-data#filtering-by-key
