### ISSUE TITLE
Query of a single field fails

### ISSUE THREAD

**Issue by vadbut** [step-up-labs/firebase-database-dotnet#261]
I have a problem with quering a single string field. I use the following C# code: 

```var username = await App.firebase.Child($"users/{uid}/username").OnceAsync<string>();```

As a result, I'm getting: `ArgumentException: Could not cast or convert from System.String to System.Collections.Generic.Dictionary 2[System.String,System.String].`

I tried different approaches like specifying the data type as Dictionary<string, string> and creating a class Username with a string variable username, however, I get the same error.

I discovered a very nasty workaround:
```
try
{
  var username = await App.firebase.Child($"users/{uid}/username").OnceAsync<string>();
}
catch (FirebaseException ex)
{
  un = ex.ResponseData.ToString();
  un = un.Substring(1, un.Length - 2);
}
```

How can I resolve the issue? If there is no real solution, is there a better workaround than getting a response from an exception?

**Comment by bezysoftware** [comment]
Use OnceSingleAsync
