### ISSUE TITLE
How to implement call back to realtime database data changed.

### ISSUE THREAD

**Issue by Jack-Paul** [step-up-labs/firebase-database-dotnet#263]
I have followed the documentation.

and implemented the same.

`client.Child("Menu")
                .AsObservable<ObservableCollection<Item>>()
                .Subscribe(
                );`

how do i get the call back using this bit confused, I am new to this, can i get some help??

**Comment by bezysoftware** [comment]
It's in the sample code: 
https://github.com/step-up-labs/firebase-database-dotnet#c-1
