### ISSUE TITLE
Setting custom key when pushing new data to firebase database

### ISSUE THREAD

**Issue by saamerm** [step-up-labs/firebase-database-dotnet#265]
Thank you for this awesome package!

I have been raking my brain for weeks trying to figure out how to set a custom key when pushing new data to the firebase real time database. 

I was trying to do this to push the data, while hoping to use the UID as the key:

    await firebase.Child("ContactUs").Child(UID)
                .PostAsync<ContactusModel>(new ContactusModel()
                { FirstName = contactus.FirstName, LastName = contactus.LastName, PhoneNumber = contactus.PhoneNumber, Email = contactus.Email, Description = contactus.Description, MainIssue = contactus.MainIssue });
                return true;

However, as you notice￼, it was adding another child with ID inside my UID: 

<img width="540" alt="ContactUs" src="https://user-images.githubusercontent.com/8262287/139629401-d47dc992-fc77-4ae3-a38a-8cc0465dbbd8.png">

I tried to search far and wide but the API's in the Google Firebase docs for Real time database are different than this package and several functions meant to do this aren't available. Close to giving up I decided to try PutAsync instead of PushAsync like this: 

    await firebase.Child("ContactUs").Child(UID)
                .PutAsync<ContactusModel>(new ContactusModel()
                { FirstName = contactus.FirstName, LastName = contactus.LastName, PhoneNumber = contactus.PhoneNumber, Email = contactus.Email, Description = contactus.Description, MainIssue = contactus.MainIssue });
                return true;

Miraculously it seems to have fixed the issue of the extra child, but I have no clue why. I also checked the docs and the source code to see what's going on but I have no clue.
<img width="538" alt="ContactUs" src="https://user-images.githubusercontent.com/8262287/139629384-a0ab58b2-0048-4487-9298-3982deeb5517.png">

Does any one have an explanation for this behavior? And is it possible use PostAsync instead of PutAsync since Put is supposed to be meant for updating and not creating a new item?

**Comment by DavidSekula** [comment]
Came here cause started using this a few hours ago and noticed the exact same thing, and was wondering if there was any downside (other than it being a Put request) in using Update to "Upsert" records, as I need my keys to match too lol

**Comment by cabauman** [comment]
No downside. PutAsync just acts as an upsert (like you said), and is the way to achieve custom keys when using this particular library.

**Comment by dave-sekula** [comment]
Cool - thanks for clarifying - perfect for what I need :)

**Comment by cabauman** [comment]
For the original poster, so you don't have to just take my word for it, I'll share a short [excerpt from the docs](https://firebase.google.com/docs/database/rest/save-data#section-put):

> Since each user will have a unique username, it makes sense to use PUT here instead of POST since we already have the key and don't need to create one.

Post is designed to create a new child node with a generated ID under the current path. Put doesn't create a new child node; it just operates on the current path.
