### ISSUE TITLE
Assign generated key to the property (ID)

### ISSUE THREAD

**Issue by L10Messi10** [step-up-labs/firebase-database-dotnet#266]
Thank you for this package.

Anyway, I have been boggling my mind in this past few weeks trying to figure out how to assign the generated key to the ID
![1](https://user-images.githubusercontent.com/49228795/140593974-b01b9c12-c041-4e3d-b28b-b9b68737b8a5.png)

As you can see above the red one must be the same as the yellow one. I have achieved such by doing this..
![2](https://user-images.githubusercontent.com/49228795/140594069-3df7695f-a63f-4486-a488-112d0c1ae6ac.png)

As you can see, my code above is embarrassing 😅, it Post first, then get the key, then post again, then delete that. To clarify it more, I can't get the generated key at the first Post, so I have to Post first to get the key then Post again to save the key, then finally delete it so it won't double the record.

Now my question is, how can we get the same key with only one Post?

**Comment by cabauman** [comment]
I don't think there's a straightforward way to achieve that. However, the [FirebaseKeyGenerator](https://github.com/step-up-labs/firebase-database-dotnet/blob/master/src/Firebase/FirebaseKeyGenerator.cs) class if public, so you can use that. [PostAsync uses that internally](https://github.com/step-up-labs/firebase-database-dotnet/blob/9ef003114a13afcad0ea78001f4acee972d9b2c6/src/Firebase/Query/FirebaseQuery.cs#L153) if the `generateKeyOffline` argument is set to true, so there should be no concerns about doing it that way.

**Comment by L10Messi10** [comment]
Thank you for the response, does the key generated guarantee uniqueness of the key??

**Comment by cabauman** [comment]
The FirebaseKeyGenerator source code says that it mimics the official Firebase generators, so I would say collisions are extremely unlikely.

If you still prefer post over put, just follow up that first PostAsync call with PatchAsync to overwrite the `Id` field. Then you won't have to do that third DeleteAsync step.

**Comment by L10Messi10** [comment]
Thank you, it solves the problem...
here's the code

`var _users= await firebaseClient.Child("Users").PostAsync(new Users
             {
                MyProperty = recorddata.Text
             });
            await firebaseClient.Child("Users").PatchAsync(new Users
            {
                Id = _users.Key,
                MyProperty = recorddata.Text
            });`

And here's how it looked in the RTDB after execution on the above codes..

![3](https://user-images.githubusercontent.com/49228795/140600941-3bb187ca-97a1-4c45-9210-be1893c8383e.png)
..

**Comment by L10Messi10** [comment]
Update about the issue, PatchAsync actually didn't solve the issue but it gives me the idea to retrieve the generated ID and finally use the PutAsync (Update) to actually update the node. Here is the full codes below.

```
var _users= await firebaseClient.Child("Users").PostAsync(new Users
             {
                MyProperty = recorddata.Text
             });
            await firebaseClient.Child("Users")
                .Child(_users.Key)
                .PutAsync(new Users
            {
                Id = _users.Key,
                MyProperty = recorddata.Text
            });
```
![4](https://user-images.githubusercontent.com/49228795/140602461-9e884f7a-624b-4d1f-b83c-7c271bfa1478.png)


As you can see, the Id is now the same as the generated Firebase ID.
