### ISSUE TITLE
adding slash before .json

### ISSUE THREAD

**Issue by syedadeel2** [step-up-labs/firebase-database-dotnet#267]
All sort of operation your library adding /.json in the URL see below:

```
public async Task<IReadOnlyCollection<StaffMember>> GetStaff()
 {
            var result = await FbClient.Child("staff")
                .OrderByKey()
                .OnceAsync<StaffMember>();

            return result.Select(x => new StaffMember(x.Object.Name, x.Key, x.Object.Email, x.Object.Role)).ToArray();
}
```

see the result

![image](https://user-images.githubusercontent.com/2682457/142754639-9c3e3479-b887-42ad-b697-efbf8ad0e27b.png)

**Comment by cabauman** [comment]
That's normal behavior, so it doesn't break functionality. There are tests [here](https://github.com/step-up-labs/firebase-database-dotnet/blob/master/src/Firebase.Tests/FirebasePathTests.cs) that specifically check for that pattern, and also a few places in the [official docs](https://firebase.google.com/docs/reference/rest/database).
