### ISSUE TITLE
EndAt() not support two arguments in firebase database.net package

### ISSUE THREAD

**Issue by person2434** [step-up-labs/firebase-database-dotnet#268]
Hello Everyone,
I'm using **Firebase Database.Net** Package  and i want to pass two arguments to `EndAt()` but this method only supports one argument
So How to Pass Two Arguments ?

thanks in advance

**Comment by cabauman** [comment]
From searching the docs and Google, it doesn't look like Firebase REST API ever supported passing multiple arguments to StartAt or EndAt.

https://stackoverflow.com/a/40514418/5984310
https://firebase.google.com/docs/database/rest/retrieve-data#section-rest-filtering

**Comment by Coding-BookMark** [comment]
thanks for the reply but you can see the rest API Response its support two arguments: [Rest Api Response](https://stackoverflow.firebaseio.com/70102492/Main/News/Categories/Education.json?print=pretty&orderBy=%22Views%22&limitToLast=10&endAt=33,%22-Mn7-ZxkUPO01iddfh2tpEn%22)
I wish you could add a feature to pass two arguments or give me a way to solve this problem
