### ISSUE TITLE
Offline database

### ISSUE THREAD

**Issue by jcampana** [step-up-labs/firebase-database-dotnet#27]
It is possible to enable Offline database with this framework?

Thanks

**Comment by bezysoftware** [comment]
It is. I've been working on it for quite some time now, but haven't documented it yet. The REST api unfortunately is pretty limited so the framework is somewhat limited, but there are workarounds. Specifically, the Offline database doesn't detect updates and deletes - only inserts. There are ways around it - one I use is to have a location "/changes/" which is incremental only and I use it to manually pull for changed / deleted items.

To get started you need also this nuget: 
Install-Package FirebaseDatabase.Platform.net -Pre
var options = new FirebaseOptions { OfflineDatabaseFactory = (t,s) => new OfflineDatabase(t, s)};
var client = new FirebaseClient("url", options);

var db = client
 .Child("dinosaurs")
 .AsRealtimeDatabase<Dinosaur>(...);

// observe the database in the same way you observe online stream
db.AsObservable().Subscribe(dino => ...);

// post data / delete data
db.Post(new Dinosaur());
db.Delete("trex");

// pull new version of data which you know changed
db.Pull("trex");

There are many other overloads / optional parameters. I intend to write a blog post explaining some of the options, but I simply don't have the time now.

**Comment by riegaz** [comment]
Hi,

your example does create an offline instance right? Can I somehow create an persistant offline database which I can reload after an application restart?

**Comment by bezysoftware** [comment]
The example should have all you need. Once subscribe to `RealtimeDatabase `the content of the offline storage gets loaded and is streamed to you via `onNext` events ( https://github.com/Reactive-Extensions/Rx.NET )

**Comment by riegaz** [comment]
Unfortunately, I do not get it. I know that the Rx.NET helps me with the events. The offline database however has to be stored somewhere on my hard drive, or do I miss something? I have to save it to a file once my application closes and reload that file and initiate it once the application starts. After that, the resync should occur.

Sorry I'm quite new to this database.

**Comment by bezysoftware** [comment]
It is all handled by the library. It indeed saves the data into a file, but you don't need to worry about that

**Comment by riegaz** [comment]
Just to make sure that I got it right. I initialize the OfflineDatabase as well as the RealtimeDatabase. At this moment they sync already? By itself? The onNext events are just the indicator which I could use to see what is going on, right?

**Comment by bezysoftware** [comment]
Yes syncing is done automatically behind the scenes.
