### ISSUE TITLE
PutAsync deletes child from the parent.

### ISSUE THREAD

**Issue by L10Messi10** [step-up-labs/firebase-database-dotnet#276]
Does PutAsync really remove its child upon update? here is my code below.

`var evaluatesch = (await client
                    .Child("Schools")
                    .OnceAsync<Schools>()).FirstOrDefault
                    (a => a.Object.SchoolID == sch_id);

                if (evaluatesch != null)
                {
                    Schools school = new Schools
                    {
                        SchoolID = schoolid,
                        SchoolName = schoolname,
                        SchoolAddress = schooladdress,
                        DateTimeSubscription = subscriptiondt,
                        Status = stat
                    };

                    await client
                        .Child("Schools")
                        .Child(evaluatesch.Key)
                        .PutAsync(school);
                    client.Dispose();
                    return true;
                }

                client.Dispose();
                return false;`

Assuming that the database has been added with another child (Teachers) then upon executing the above code which updates the parent node, the child (Teacher) will be deleted. Here is the screenshot after executing the above code.

![putasyncfirebase](https://user-images.githubusercontent.com/49228795/154825426-18799e42-7183-4197-b77b-80a2a607fad4.png)
.

**Comment by cabauman** [comment]
You didn't add a _before_ screenshot so I assume Teachers is a child of School. In that case, yes, put replaces the whole node. You can either include teachers in your put operation or use patch instead of put.

**Comment by L10Messi10** [comment]
Yes, (Teachers) is the child of the School. Thank you for your feedback PatchAsync solved the issue.
