### ISSUE TITLE
Attempt to Update just the file location

### ISSUE THREAD

**Issue by eduardoagr** [step-up-labs/firebase-database-dotnet#277]
I have a child Notes, and I want to update just the file location

`public async void UpdateNotebookNote(string Id, string FileLocation) {

            await firebaseClient
                .Child(AppConstant.Notes)
                .Child(Id)
                .PatchAsync(FileLocation);
        }`

but when I do this, I get this exception

`public async void UpdateNotebookNote(string Id, string FileLocation) {

            await firebaseClient
                .Child(AppConstant.Notes)
                .Child(Id)
                .PatchAsync(FileLocation);
        }`

**Comment by cabauman** [comment]
You didn't include the exception (looks like a copy/paste mistake). And you didn't include any details about your db structure (e.g. what properties the Note object has).

**Comment by cabauman** [comment]
One more question.

> .PatchAsync(FileLocation);

Is FileLocation a string?

**Comment by cabauman** [comment]
It needs to be an object

```
.PatchAsync($"{ \"FileLocation\" : \"{FileLocation}\" }");
```

**Comment by eduardoagr** [comment]
why do I have to put \

**Comment by cabauman** [comment]
It's json so we have to escape the quotes. I hope it helped.

**Comment by eduardoagr** [comment]
yes thank you @cabauman
