### ISSUE TITLE
Help with PutAsync compile error

### ISSUE THREAD

**Issue by steveharan** [step-up-labs/firebase-database-dotnet#28]
I can read ok - now trying to update a value.  But I can't get over this compiler error:

"Cannot assign void to an implicitly-typed variable"

My firebase data:

104837
.....newMessage: 
.............false

My code:
            bool newval = true;

            var result = await firebase
              .Child("104837")
              .Child("newMessage")
              .WithAuth(auth.FirebaseToken)
              .PutAsync(newval);

I must be doing something fundamentally wrong...

Thanks!

Steve

**Comment by steveharan** [comment]
The same if I add this to your demo Dinosaur project:

            var dino = await firebase
  .Child("dinosaurs")
  .Child("t-rex")
  .PutAsync(new Dinosaur());

"Cannot assign void to an implicitly-typed variable"

(The above putasync code taken from the readme)

**Comment by steveharan** [comment]
Could you include in the demo code a putasync?

**Comment by steveharan** [comment]
No compile error on postasync:

var dino = await firebase
  .Child("dinosaurs")
  .PostAsync(new Dinosaur());

**Comment by seminmusic** [comment]
I face the same issue, for temporary solution omit variable definition:
`await firebase`
  `       .Child("dinosaurs")`
  `       .Child("t-rex")`
  `       .PutAsync(new Dinosaur());`
But this way we can't get anything from Firebase response.
It would be nice to fix that.

**Comment by bezysoftware** [comment]
What exactly are you expecting to be the result? It would only return the same object you give it (`new Dinosaur()`)

**Comment by seminmusic** [comment]
Maybe result can contain generated key(s) like one in `PostAsync`? Since `PutAsync` returns void, I think that example should be updated to avoid misunderstanding. By the way, great work.

**Comment by bezysoftware** [comment]
But Put and Patch don't generate new keys. They only write data to specified location. PostAsync is the only method which generates new key
