### ISSUE TITLE
How to Query FirebaseRTDB?

### ISSUE THREAD

**Issue by L10Messi10** [step-up-labs/firebase-database-dotnet#301]
I would like to use the query in firebasedatabase like this in SQL `Select * From Users where Firstname like " + entryname.Text +"`
How can I do this in firebasedatabase.net RealtimeDatabase?

I've attached an image on my RTDB

![rtdb](https://user-images.githubusercontent.com/49228795/196012186-fd017ab0-9f93-4217-b611-676e5da1b58d.png)

**Comment by jaybowman** [comment]
I hope this will help. First you need to have an index on the property you want to query.
```
var query = await _fbClient.Child(_userCollection)
                            .OrderBy("firstName")
                            .StartAt("Jimmy")
                            .OnceAsync<Mynamespace.Firebase.User>();

       var list = query.ToList();
```

**Comment by L10Messi10** [comment]
> I hope this will help. First you need to have an index on the property you want to query.
> 
> ```
> var query = await _fbClient.Child(_userCollection)
>                             .OrderBy("firstName")
>                             .StartAt("Jimmy")
>                             .OnceAsync<Mynamespace.Firebase.User>();
> 
>        var list = query.ToList();
> ```

Thank you for the reply, after trying your code, seems like it doesn't do the query itself. It just gets the first data of the tree. In my attached image, Querying the data "Allan" the result just fetches the "sdsd" in the data tree, I also added another data with the FirstName "Allan" on the list to confirm my suspicion and I can confirm that it does only fetch the first data.

**Comment by L10Messi10** [comment]
I did a little tweak on your code @jaybowman and got things working. This is the code.

//Getting the list of the users
` public async Task<List<Users>> GetAllUsers()
        {

            return (await client
                .Child("Users")
                .OnceAsync<Users>()).Select(item => new Users
            {
                FirstName = item.Object.FirstName,
                LastName = item.Object.LastName
            }).ToList();
        }`

//Applying query to the users with a specific query. First I called the "GetAllUsers" function to fill the List
//and then querying that particular List. Tell me if I'm doing it cleverly or if I'm just being Lazy. 😅😅

`public async Task<List<Users>> FindUser(string fname)
        {
            var queryUsers = await GetAllUsers();
            await client
                .Child("Users")
                .OnceAsync<Users>();
            return queryUsers.Where(a => string.Equals(a.FirstName, fname, StringComparison.CurrentCultureIgnoreCase)).ToList();
        }`
