### ISSUE TITLE
No Key is returned

### ISSUE THREAD

**Issue by pashaUSA** [step-up-labs/firebase-database-dotnet#305]
Trying to use the PostAsync method but the Key value is returned, it is not even on the list of available properties

var record= new { Name = "Firebase", Desc = "C#" };
var response = _firebaseClient.Child("Record").PostAsync(record);
What am I missing?

**Comment by bezysoftware** [comment]
You need to await the PostAsync method. See https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/
