### ISSUE TITLE
Cannot remove the node

### ISSUE THREAD

**Issue by paymok** [step-up-labs/firebase-database-dotnet#32]
I am writing the program for delete the node but no work
Here's my code.

```
FirebasClient client2 =new FirebaseClient("http://XXXXXX.firebaseio.com/");
var nodelist= client2.Child("log");
await nodelist.DeleteAsync();
```

Also, may I know how to update or delete the values base on the where clause?

**Comment by bezysoftware** [comment]
What is the error?

**Comment by paymok** [comment]
Oops~ I fixed this issue due to auth right
