### ISSUE TITLE
Query problem

### ISSUE THREAD

**Issue by paymok** [step-up-labs/firebase-database-dotnet#33]
Refer to Firebase "https://dinosaur-facts.firebaseio.com/"
How can I write the query if the dinosaur of height is greater than 1 in descending order

**Comment by paymok** [comment]
Seems work now

Using HTML

```
const rootRef= firebase.database().ref();
const heightRef = rootRef .child('dinosaurs').orderByChild('height').startAt(0.9);
```

Using C#

 ```
var firebase = new FirebaseClient("https://dinosaur-facts.firebaseio.com/");
                var dinos = await firebase
                  .Child("dinosaurs")
                  .Child("")
                  .OrderBy("height")
                  .StartAt(0.9)
                  .OnceAsync<Dinosaur>();
```

My question is "if I want to retrieve all of the dinosaurs names, I should use '.Child(""),' as a wildcard right?"

**Comment by bezysoftware** [comment]
```
var dinos = await firebase
  .Child("dinosaurs")
  .OrderBy("height")
  .StartAt(1)
  .OnceAsync<Dinosaur>();
```

This isn't gonna work on the sample dinosaurs repo because it requires you to have an index on the element you use for ordering - in this case "height". And the sample repo doesn't have this index.

**Comment by paymok** [comment]
Thank you for help. So I have to do the ordering in programming code :-)
