### ISSUE TITLE
Save Data as Transactions

### ISSUE THREAD

**Issue by riegaz** [step-up-labs/firebase-database-dotnet#34]
Are those transactions already implemented? I guess they are quite helpful.

https://www.google.com/url?sa=t&source=web&rct=j&url=https://firebase.google.com/docs/database/web/read-and-write%23save_data_as_transactions&ved=0ahUKEwjc46_w85DRAhXBRiYKHRmJDEEQygQIKjAC&usg=AFQjCNEq7nEHHw2Sj8otFg5kE_cCwg3s8g&sig2=nUuwe9U5e_gKVWDlHFdjqg

**Comment by bezysoftware** [comment]
AFAIK it isn't possible with current REST api: https://firebase.google.com/docs/database/rest/save-data
