### ISSUE TITLE
Is it possible to add multi-conditions into the query

### ISSUE THREAD

**Issue by paymok** [step-up-labs/firebase-database-dotnet#35]
Sorry it's me again. I would like to write the query to search the member who is female and height is greater than 170cm.

In URL query, it should look like that
https://xxxx.firebaseio.com/profiles/.json?orderBy="sex"&equalTo="f"&orderBy="height"&startwith="170"

But I can't write more than two conditions in c# like that
            var ddd = client 
                  .Child("profiles") 
                  .OrderBy("sex")  
                 .equalTo("f")
                  OrderBy("height")  
                 .startwith("170")
                 .OnceAsync<Profiles>();

**Comment by bezysoftware** [comment]
This is not possible. You cannot have the same parameter in URL multiple in times

**Comment by paymok** [comment]
But run the query via firebase's get method, they can handle multiple parameters and values

**Comment by bezysoftware** [comment]
If I try this: https://dinosaur-facts.firebaseio.com/dinosaurs.json?print=pretty&orderBy=%22$key%22&startAt=%22pterodactyl%22&orderBy=%22height%22&startAt=4
I can see that the 2nd "orderby" and "startAt" are ignored. They only take the first set

**Comment by paymok** [comment]
thanks. I got it!
