### ISSUE TITLE
Object key

### ISSUE THREAD

**Issue by riegaz** [step-up-labs/firebase-database-dotnet#39]
When I execute `Post(new Client(){name = "client1"})` it gives

`{
  "parent" : {
    "clients" : {
      "a123" : {
        "-KbGy8X22UEbtUnTJNKh" : {
          "name" : "client1"
        }
      },
      "info" : "data"
    }
  }
}
`

But what I want is:

`{
  "parent" : {
    "clients" : {
      "a123" : {
          "name" : "client1"
      },
      "info" : "data"
    }
  }
}`

What do I have to change?

**Comment by bchanampa** [comment]
I have same problems, looking in the code from repository I discovered other method for realize insert/update. Look **Patchsync** work for me for now.

**Comment by riegaz** [comment]
Perfect, exactly what I wanted.

**Comment by lucazin** [comment]
Hello.

Im trying to update a

 single node value ( just a stirng with code product ) but gives a error.

 await firebaseClient.Child("ESTABID_17").Child("PEDIDOS_DELIVERY").Child("-Lzhy-dZ9iFiJ823q9sMQ/codigoPedido").PatchAsync("213");

What can i do?
