### ISSUE TITLE
An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set

### ISSUE THREAD

**Issue by lyquocnam** [step-up-labs/firebase-database-dotnet#4]
i tried as picture, so this error, please help !

`An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set`

![image](https://cloud.githubusercontent.com/assets/8347826/16508089/91354a96-3f59-11e6-9232-a392cc2af3a8.png)

**Comment by bezysoftware** [comment]
You're right! I will work on a fix asap

**Comment by bezysoftware** [comment]
The fix was released in v1.1.5
