### ISSUE TITLE
Could not Cast from String to Dictionary[string,string]

### ISSUE THREAD

**Issue by technochris1** [step-up-labs/firebase-database-dotnet#40]
I have a collection that has Mixed objects. All objects are unique keys, but the data in that object is different. Some contain just a String:

-KWk_LncstV5y8afZwix: "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQE..."

And Some contain 2 strings.

-KWklE2NYsw7QqhQl1yf:
        Id: "-KWkkJb67cDMZFOGMluK"
        sig: "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQE..."

When querying this data I get "An exception of type 'Firebase.Database.FirebaseException' occurred in mscorlib.dll but was not handled in user code". I've tried several things to attempt to cast this, but every time I get the same error. I'm assuming my data isn't what the parser is expecting. 

to solve the 2 types in one collection, I capture the error in a try/catch, and if fail, trying secondary type.

**Comment by bezysoftware** [comment]
This is the price for having the library strongly typed - you can't mix 2 types into one collection. I'm not aware of any suitable workaround other than what you already posted

**Comment by technochris1** [comment]
Thanks for the reply. Thank you for your work on this.
