### ISSUE TITLE
There is no database secret for firebase database anymore

### ISSUE THREAD

**Issue by mzd555** [step-up-labs/firebase-database-dotnet#44]
There is no database secret for firebase database anymore, so without that how do we authenticate as an admin from the server.

**Comment by KennyLee-Taiwan** [comment]
You can "Authenticate with email and password" as described [here](https://medium.com/step-up-labs/firebase-authentication-c-library-8e5e1c30acc2#.kbbpizsab).

If you really still want to use your database secret, it can be accessed like [this](http://stackoverflow.com/questions/37418372/firebase-where-is-my-account-secret-in-the-new-console).

**Comment by mzd555** [comment]
thanks for the reply, with "Authenticate with email and password" how do I manage the database as an admin rather than just a user?

**Comment by bezysoftware** [comment]
I don't think you can login as an admin with email and password. Theoretically you can alter your database rules to allow this special user access to your entire repository but it is easier to go with the legacy DB secret

**Comment by imran-maher** [comment]
how to connect esp8266 with firebase . i used auth and host but it is not working .
any one can help me..?
