### ISSUE TITLE
Post Data with our specified key

### ISSUE THREAD

**Issue by efftronicsit** [step-up-labs/firebase-database-dotnet#47]
Hi, i found good library after googling on Firebase Database API from C#. this library is working fine. 
I want to push my data into Firebase Real Time Database with our **specified key** (not automated generated key). Please suggest solution of my problem.
Thanks in advance.

**Comment by micdoug** [comment]
Hi. This library is really great.
I use the following approach:

// the base reference 
var ref = client.Child("users");
// create an user with a specif key
await ref.Child(key).PutAsync(data);

Hope it helps.

**Comment by bezysoftware** [comment]
As @micdoug posted you can use PutAsync, or you can use PatchAsync. Here are the official REST docs: https://firebase.google.com/docs/reference/rest/database/

**Comment by efftronicsit** [comment]
Its working fine, Thank you to @micdoug  & @bezysoftware

**Comment by efftronicsit** [comment]
Thanks to @stepuplabs
