### ISSUE TITLE
How to auth with firebase when connect to client ?

### ISSUE THREAD

**Issue by lyquocnam** [step-up-labs/firebase-database-dotnet#5]
Hi auth, i see the second param on client ` var firebase = new FirebaseClient(uri, ... );` but how to use it ?
please help !

**Comment by bezysoftware** [comment]
Hi,

the second param is a `Func<Task<string>>`. so it can look something like this:

`var firebase = new FirebaseClient(uri, () => Task.FromResult("my-secret-key") );`

If you want to be able to authenticate your user with facebook / google you can use [FirebaseAuthentication.net](https://github.com/step-up-labs/firebase-authentication-dotnet) and use something similar (func returning a Task).

**Comment by lyquocnam** [comment]
thanks so much, i will try for this !
