### ISSUE TITLE
Posting multiple objects with customized keys

### ISSUE THREAD

**Issue by efftronicsit** [step-up-labs/firebase-database-dotnet#51]
Posting of single object is working fine either using Push or Put. 
When I pass a List of Objects,  posted successfully but it was posted as key as Object Index.
Please see below image for reference.

![fb db info](https://cloud.githubusercontent.com/assets/26621482/24867750/dc32ad16-1e2b-11e7-900e-a83b85feb0d9.png)

How to resolve it.

**Comment by micdoug** [comment]
Simple post a Dictionary<string, object> where the key is the desired key for each object.

**Comment by efftronicsit** [comment]
Thank you, it's working awesome. 
Is there any limit Request Data size to post or Put.

**Comment by micdoug** [comment]
Cool :). I have used this approach to post about 2 thousand objects with 10 properties (2 ints, and 8 strings) and it works. I don't know if there is any limit. Maybe we can find it on firebase web client original docs.

**Comment by efftronicsit** [comment]
Yesterday i was upload 25,000 objects with 11 parameters (4 ints, 7 strings), Its working without issue. 
Thank you

**Comment by nico75005** [comment]
You're not using this library to do that right?
Otherwise, how do you do it as **PatchAsync**, **PutAsync** and **PostAsync** only accept a string and not a **Dictionary**

Thanks
