### ISSUE TITLE
Can't access WithAuth(string token)

### ISSUE THREAD

**Issue by E4est** [step-up-labs/firebase-database-dotnet#55]
I think you made a mistake in QueryExtensions.cs

Instead of
`internal static AuthQuery WithAuth(this FirebaseQuery node, string token)`
it should be
`public static AuthQuery WithAuth(this FirebaseQuery node, string token)`

Or do I get something wrong?

**Comment by bezysoftware** [comment]
This is by design, WithAuth shouldn't be used by external code. Correct way to use credentials is in the readme - via `FirebaseOptions`

**Comment by E4est** [comment]
Yes, this is where my confusion came from, thanks!
