### ISSUE TITLE
OfflineDatabase Sync

### ISSUE THREAD

**Issue by HACKATHONCAMPINAS** [step-up-labs/firebase-database-dotnet#56]
How do I synchronize data that is offline with the online database?
Could you give me an example?

**Comment by bezysoftware** [comment]
That's done automatically. See https://github.com/step-up-labs/firebase-database-dotnet/tree/master/samples/OfflineChat

**Comment by HACKATHONCAMPINAS** [comment]
It worked, it is sending the device data to the base, but if I add or remove some registry in the base it is not updated on the device ... Am I doing something wrong? 
This is my code:


protected async override void OnCreate (Bundle bundle)
		{

            base.OnCreate(bundle);
           
            SetContentView(Resource.Layout.Main);
          
            var client = new FirebaseClient("https://mydatabase.firebaseio.com/",
                new FirebaseOptions
                {
                    OfflineDatabaseFactory = (t, s) => new OfflineDatabase(t, s)                    
                });


            var messagesDb = client.Child("offlinemessages").AsRealtimeDatabase<Messages>();
            var authorsDb = client.Child("offlineauthors").AsRealtimeDatabase<Author>();
            
            authorsDb.SyncExceptionThrown += (s, ex) => Console.WriteLine(ex.Exception);
            messagesDb.SyncExceptionThrown += (s, ex) => Console.WriteLine(ex.Exception);            
            
			Button btnUpdate = FindViewById<Button> (Resource.Id.btnUpdate);
            Button btnCreateNew = FindViewById<Button>(Resource.Id.btnCreateNew);
            ListView listView = FindViewById<ListView>(Resource.Id.listView1);

            btnUpdate.Click += async delegate {
                
                var _authorsDb = client.Child("offlineauthors").AsRealtimeDatabase<Author>();
                
                ArrayAdapter adapter = new ArrayAdapter(this, 
					Android.Resource.Layout.SimpleListItem1, 
					_authorsDb.Database.Values.ToList());
					
                listView.Adapter = adapter;               
            };

            btnCreateNew.Click += delegate {

                var myKey = authorsDb.Post(new Author 
				{ 
					Name = "AUTHOR TESTE_" + new Random().Next().ToString() 
				});
				
                messagesDb.Post(new Messages 
				{ 
					Author = myKey, 
					Content = "MESSAGE TEST_" + new Random().Next().ToString() 
				});               
            };
        }

**Comment by bezysoftware** [comment]
You never subscribe to `messagesDb` or `authorsDb`. They are cold observables which don't produce any events until subscribed to. 
I suggest reading about Rx: www.introtorx.com

**Comment by shkar62** [comment]
I have been trying out the same example for offline database. But i am getting this error:
Object reference not set to an instance of object , source : mscorlib at lex.db.initialise() method. 
Please help

**Comment by bezysoftware** [comment]
Did you install the Platform nuget into you target platform project?

**Comment by felipeoliveirar** [comment]
How i use this pagckge with Xamarin.Forms ? It doens't recognize it.

**Comment by shkar62** [comment]
@felipeoliveirar  You can install this package with Xamarin.Forms. You have to change your PCL profile to PCL4.6 Profile 44 in the portable project
![screen shot 2017-08-16 at 10 05 02 am](https://user-images.githubusercontent.com/29039813/29347459-6d081266-826a-11e7-84d5-a1e7ad68ba90.png)

**Comment by felipeoliveirar** [comment]
Thanks shkar62

**Comment by felipeoliveirar** [comment]
There isn't this option os VS 2017

**Comment by pallavbohara** [comment]
@felipeoliveirar 
 In VS, first you have to unload the PCL project to edit its .csproj file.
Here is screenshot.
![image](https://user-images.githubusercontent.com/23195991/29396316-cdbc755a-8334-11e7-9971-d19d75ae7c41.png)

**Comment by ornolisvt** [comment]
How I can update the offline items? I have a offline database that sync with Firebase Database. But, when I change a item in Stores database on Firebase, don´t notified the change. I use this code:
var client = new FirebaseClient(firebaseDatabaseUrl, new FirebaseOptions
                               {
                                   AuthTokenAsyncFactory = () => Task.FromResult(authToken),
                                   OfflineDatabaseFactory = (t, s) => new OfflineLiteDb(t, s),
                               });

                var storesDB = client
                  .Child("Stores")
                  .AsRealtimeDatabase<Store>(pushChanges: false);

                storesDB
                .AsObservable()
                .Subscribe((x) => Console.WriteLine($"Key: {x.Key}, Event: {x.EventType.ToString()}, Source: {x.EventSource.ToString()}"));
