### ISSUE TITLE
System.IO.FileNotFoundException: Could not load assembly 'System.Runtime.InteropServices.WindowsRuntime

### ISSUE THREAD

**Issue by tbsAakshay** [step-up-labs/firebase-database-dotnet#58]
I am getting following exception at build time. I am trying to implement code for 

Severity	Code	Description	Project	Path	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'System.Runtime.InteropServices.WindowsRuntime.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	Test2.Android				

I am just trying to get simple token as you shown but result is exception.

var auth = "xxxxxxxxxxxxxxxxxxxx"; // your app secret
            var firebaseClient = new FirebaseClient(
              "FirebaseAppUri",
              new FirebaseOptions
              {
                  AuthTokenAsyncFactory = () => Task.FromResult(auth)
              });
Can you please help me in this.

**Comment by micdoug** [comment]
This seems to be a problem related to System.Reactive version 3.0+.
I found a work around for this. Just remove System.Runtime.InteropServices.WindowsRuntime from your references. This package is not required by xamarin.android.
It works for me.

**Comment by bradintheusa** [comment]
I agree with this solution.  Remove it from packages.

`packages\System.Runtime.InteropServices.WindowsRuntime.4.0.1\lib\netstandard1.3`

**Comment by Qwesaqwes** [comment]
I solved the problem by adding this file in the "/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades"

[https://www.dropbox.com/home/Public?preview=System.Runtime.InteropServices.WindowsRuntime.dll](url)

**Comment by Qwesaqwes** [comment]
I solved by adding this file
"/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades"

[https://www.dropbox.com/s/zwztxnxhrqffp8q/System.Runtime.InteropServices.WindowsRuntime.dll?dl=0](url)

**Comment by Qwesaqwes** [comment]
I solved the prob by adding this file
https://www.dropbox.com/sh/kaa7vqzzj1d2zbs/AADpGMBOHQDmuWxlaVY_Rv0Pa?dl=0

in
/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades
