### ISSUE TITLE
Connecting Database with Authentication

### ISSUE THREAD

**Issue by kanwal019** [step-up-labs/firebase-database-dotnet#60]
Is there any documentation on firebase database connect using email and password authentication ?

**Comment by bezysoftware** [comment]
https://github.com/step-up-labs/firebase-authentication-dotnet
https://medium.com/step-up-labs/firebase-authentication-c-library-8e5e1c30acc2

**Comment by kanwal019** [comment]
I have already been through these, I am able to authenticate the firebase user. The problem is the connection to the firebase DB after the authentication.

**Comment by kanwal019** [comment]
Since I have implemented the Firebase DB rules, I am not able to retrieve/write data.

**Comment by TFAstudio** [comment]
We have managed to get the Email/Password authentication working within the FirebaseDatabase.net package, using FirebaseAuthentication.net package.  It was not quite so straight forward, but you must ensure you have an email and password associated in the database via the Firebase Console that Google provide through their webpage.

Here is a little sample of how we did it.

<pre>
firebaseUrl = "https://YOURDATABASE.firebaseio.com/";

// The following username and password connections are created 
// in the firebase console via https://console.firebase.google.com
// For more information see https://firebase.google.com/docs/auth/web/password-auth
firebaseUsername = "firebaseuser@yourdomain.com";
firebasePassword = "PasswordCreatedOnFirebaseConsole";

// this can be found via the console
firebaseApiKey = "YourApiKey";

var auth = new FirebaseAuthProvider(new FirebaseConfig(firebaseApiKey));
// this grabs a one-off token using the username and password combination
await token = auth.SignInWithEmailAndPasswordAsync(firebaseUsername, firebasePassword);

// finally log in
var firebaseClient = new FirebaseClient(
						firebaseUrl,
						new FirebaseOptions
						{
							AuthTokenAsyncFactory = () => Task.FromResult(token.FirebaseToken)
						});
						
// now you can make your query
var results = await firebaseClient
                .Child("users")
                .OnceAsync<Models.User>();

</pre>

**Comment by bezysoftware** [comment]
You don't need to have the user created beforehand, the Auth library has a Create method which lets you create the user from code

**Comment by S00015918** [comment]
Which Nuget package to use FirebaseClient please ?
