### ISSUE TITLE
Observable raises first value only after about 15 seconds

### ISSUE THREAD

**Issue by micdoug** [step-up-labs/firebase-database-dotnet#61]
Hi. I am using this library in a xamarin android project. 
I have problems when using the realtime functionality.
For example, when I use:

` client.Child("contacts").AsObservable<Contact>().Subscribe ..... `

The first value only arrives after about 15 seconds. After the first value the changes are raised instantly.
What can I do to improve this?

Thanks in advance.

**Comment by micdoug** [comment]
This happens in Xamarin.Android. I tested right now with a windows forms project and the delay is acceptable (between 2 and 5 seconds).

**Comment by yohaas** [comment]
I'm seeing 2 seconds when the message is added. Changes are immediate though. Is there any way to speed it up for new messages? Other libraries I've tried (while inferior in just about every other way) do send the new messages immediately. 
I'm using Windows Forms. 

2 seconds per message is an issue for me. I could have several thousand messages to go through and they are coming in 2 seconds apart.

**Comment by cabauman** [comment]
I'm having this problem, as well, except it's taking about 30 seconds (no exaggeration). 16 objects, each with only 6 members. This is for a UWP app. OnceAsync accomplishes the same task in about 2 seconds.

**Comment by eclipsed4utoo** [comment]
@cabauman (or anyone else) 

I know it's been a while, but did you happen to find a fix for this. I'm literally having the same problem where the subscribe takes exactly 30 seconds before data starts coming in.

```
1/19/2019 6:35:56 PM
1/19/2019 6:36:26 PM - -LRTJwKMeiOLZneyM_cn
1/19/2019 6:36:26 PM - -LRTNBajR7J2oGXhJkCu
1/19/2019 6:36:26 PM - -LRTzGmI6MVfXCKlPB_t
```
(printing out the time and the keys of the objects when they come in)

This is pretty frustrating and basically makes this library useless.

**Comment by cabauman** [comment]
@eclipsed4utoo which platform? I mainly use Xamarin (haven't tried UWP in quite some time) and I haven't experienced this issue since I posted over a year ago.

**Comment by eclipsed4utoo** [comment]
@cabauman I'm using it in Xamarin Forms, but specifically running it on iOS. I haven't tested Android yet.

**Comment by cabauman** [comment]
@eclipsed4utoo okay I'll try it too and see if I experience the same issue. I'll get back to you.

**Comment by cabauman** [comment]
I experienced the issue with Xamarin.Forms.iOS but not with Xamarin.Forms.Android. I'll have to try some more debugging.

**Comment by eclipsed4utoo** [comment]
So I was able to get it to work by doing this...

```
var child = firebase.Child("post-comments");
var observable = child.AsObservable<object>();
var sub = observable.Where(t => t.Key == _post.ID).Subscribe(t => {
     var container = (JContainer)t.Object;
     var commentIDs = container.Select(c => c.Path).ToList();
     var commentChildSub = firebase.Child("comments").AsObservable<Comment>().Where(com => commentIDs.Contains(com.Key)).Subscribe(async newComment => {
           var comment = newComment.Object;
           Device.BeginInvokeOnMainThread(() => {
		if (Comments == null)
		     Comments = new ObservableCollection<CommentCellViewModel>();
     
                var set = new SortedSet<Comment>(Comments.Select(c => c.Comment).ToList());
		set.Add(newComment.Object);
	        Comments = new ObservableCollection<CommentCellViewModel>(set.ToList().Select(s => new CommentCellViewModel(s)));
          });
     });
});
```

So I'm basically subscribing to the root `post_comments` child and using the `Where` with the post ID, then when I get the comment IDs, I subscribe to the `comments` child and only handle those from the commentIDs list.

However, this is still painfully slow. While it's not the "30 seconds until data starts coming in", it takes about 1.1 seconds to just get 3 comments for the post I am testing with.

Is there any explanation to what using the `Where` clause with the observable and subscribe does?

And am I really subscribing to the entire `post-comments` store and just ignoring the posts that I don't care about? Because that would seem really really inefficient.

**Comment by bdbehrho** [comment]
Although not ideal, I have worked around this in the past by retrieving the entire collection manually before I begin listening. New updates seem to come in without the delay so this works as long as your subscription function can handle getting the same object multiple times.

```
public virtual async Task<List<T>> GetAll()
{
    var items = await _firebaseClient
        .Child(CollectionEndpoint)
        .OnceAsync<T>();

    return items.Select(firebaseObject => ConvertFirebaseObjectToModel(firebaseObject)).ToList();
}


public virtual async void ListenForChanges(Action<T> onUpdate)
{
    var existingItems = await GetAll();

    foreach(var item in existingItems)
    {
        onUpdate(item);
    }

    _firebaseClient
        .Child(CollectionEndpoint)
        .AsObservable<T>()
        .Subscribe(d => onUpdate(ConvertFirebaseObjectToModel(d)));
}

// Key is stored on a JsonIgnore'd Id property on model to make patching single object easier
protected virtual TModel ConvertFirebaseObjectToModel<TModel>(FirebaseObject<TModel> firebaseObject) where TModel : IHasId
{
    TModel model = firebaseObject.Object;
    model.Id = firebaseObject.Key;
    return model;
}
```

**Comment by bdbehrho** [comment]
I haven't had any issues with performance but I've only used it on small collections (< 50 records). My workaround will result in pulling in the same data twice so if you're observing a large amount of data it's probably not a great solution. I haven't found a better workaround unfortunately.

**Comment by TennisDrum** [comment]
I'm having this same issue. I'm new to Xamarin and C#, but have used Firebase from XCode for iOS development for a while. It's always been blazing fast. So, I've wanted to stick with it. I've built a test app to learn the interactions with Firebase, and even with just a 5 record dataset it's taking 30 seconds for the initial data download. Updates through .Subscribe are received instantaneously. I get the same results regardless of Android or iOS simulator. Get same result on iOS physical device (don't yet have an Android physical device).

My code:
`void Handle_GetData(object sender, System.EventArgs e)
    {
        Console.WriteLine("***** Starting to fetch data *****");

        try
        {
            receivedStudents = firebase
            .Child("StudentsTest")
            .AsObservable<Student>()
            .Subscribe(d => Console.WriteLine(d.Object.Name));

        }

        catch (FirebaseException ex)
        {
            Console.WriteLine("*** ERROR caught ***");

        }

    }`

The Console output (note the timestamps from "Starting to fetch data" to the names being output). Also not the "ERROR" in catch is not executed:
2019-02-24 13:56:10.687941-0600 FirebaseTest3.iOS[17662:1526354] ***** Starting to fetch data *****
Thread started: <Thread Pool> #9
Thread started: <Thread Pool> #10
Thread started: <Thread Pool> #11
Thread started: <Thread Pool> #12
Thread started: <Thread Pool> #13
Thread finished: <Thread Pool> #12
Thread finished: <Thread Pool> #8
2019-02-24 13:56:41.243104-0600 FirebaseTest3.iOS[17662:1526611] Ernesto
2019-02-24 13:56:41.243301-0600 FirebaseTest3.iOS[17662:1526611] Henry
2019-02-24 13:56:41.243424-0600 FirebaseTest3.iOS[17662:1526611] Joe
2019-02-24 13:56:41.243554-0600 FirebaseTest3.iOS[17662:1526611] Joe2
2019-02-24 13:56:41.243744-0600 FirebaseTest3.iOS[17662:1526611] SelvaChange
