### ISSUE TITLE
Does not handle array data

### ISSUE THREAD

**Issue by briandunnington** [step-up-labs/firebase-database-dotnet#63]
Data that is stored with numeric keys in (mostly) sequential order will be treated like arrays in Firebase and returned as arrays in the REST API (more info here: https://firebase.googleblog.com/2014/04/best-practices-arrays-in-firebase.html)

Fixed in PR #62 - Previously, this data threw an exception because the JSON deserialization could not convert the array data to a dictionary. Now if the data looks like an array, it is correctly deserialized with the correct keys.

**Comment by bezysoftware** [comment]
Is it really a good idea to have data as array in firebase db? From what I remember streaming will not work for arrays

**Comment by briandunnington** [comment]
The link I posted has Firebase's view on using array data in Firebase (TLDR: often a different approach is better, but sometimes arrays are the right thing). In any event, Firebase fully supports storing array data and the REST API supports arrays over the streaming connection, which is how I encountered this bug in the first place, so it is nice for this library to handle that type of incoming data.
