### ISSUE TITLE
PostAsync(T object)

### ISSUE THREAD

**Issue by johnjake** [step-up-labs/firebase-database-dotnet#64]
Thank you guys for the hard work I was wondering if this is possible instead of using a pain json string using T object    "await _firebase.Child(table).PostAsync(entity);"

Thanks

**Comment by TFAstudio** [comment]
Not sure what you are asking.  There's already a PostAsync(entity) that will push a new entity onto the Table you select in your query...  and by default will create a new entity Id based on the Firebase protocol so it gets put at the end of the list...  The method returns the object-key value pair just like any other query.

Give it a shot and see if you can achieve that!

**Comment by johnjake** [comment]
Thanks a lot its working now and it returns the object-key :D
