### ISSUE TITLE
How to update with multiple where condition clause

### ISSUE THREAD

**Issue by johnjake** [step-up-labs/firebase-database-dotnet#65]
#```
account_profile
         -Kk5Xv3E0kqlh6HJSGJ4
          email: "jake@yahoo.com"
          homecity: "NC"
          uid: "0002"

```
Good Day! How do I update the above Firebase string similar to SQL statement, I am relatively new to document type db. Thanks a lot. 

UPDATE account_profile SET email = 'myemail@exm.com', homeCity='ZXFD' WHERE  homeCity = 'NC' AND uid = '0002'

**Comment by bezysoftware** [comment]
Hi, that's not possible. You can only update individual nodes. Read the official docs https://firebase.google.com/docs/database/

**Comment by TFAstudio** [comment]
You have an uid.  I assume this is a primary key of some sort.  Firebase is not a relational database but a NoSQL database that you can use to mimic relational qualities.
https://firebase.google.com/docs/database/rest/structure-data

If you really needed to update a group of information, query nodes that contain the homeCity you are looking for, then patch each node in a loop that needs to be updated.
