### ISSUE TITLE
Empty line in between every message

### ISSUE THREAD

**Issue by yohaas** [step-up-labs/firebase-database-dotnet#67]
I downloaded the source and I see that this gets called in between each message that I receive:

(in FirebaseSubscription.cs)
```
 if (string.IsNullOrWhiteSpace(line))
 {
    await Task.Delay(2000).ConfigureAwait(false);
    continue;
}
```
Is it normal to have a blank line sent after every message? 
Also, is a 2 second delay really necessary? Is a delay needed at all - if it is, can it be shortened?

**Comment by bezysoftware** [comment]
Yes the server sends an empty line after each pair of event & data, e.g.

```
event: <event>
data: <data>
<emptyline>
```

I suppose the delay is not really necessary, I will remove it

**Comment by yohaas** [comment]
Thanks! I downloaded the source and changed it to 100ms with no apparent side effect. Good to know that it's not needed.
