### ISSUE TITLE
PostAsync with auth and generateKeyOffline=true generates invalid url

### ISSUE THREAD

**Issue by briandunnington** [step-up-labs/firebase-database-dotnet#69]
If you use WithAuth() and PostAsync() with generateKeyOffline=true, the url that is generated is invalid. The url has the new key + .json is appended to the end after the auth token.

This code:
            var firebase = new FirebaseClient("http://base.path.net");
            var x = firebase.Child("child").WithAuth(() => "token").PostAsync("test string");

Produces this url:
            http://base.path.net/child/.json?auth=token-KkRv2_9xeHTm9xtBxzS/.json

But the correct url should have been:
            http://base.path.net/child/-KkRv2_9xeHTm9xtBxzS/.json?auth=token

**Comment by briandunnington** [comment]
@bezysoftware Any comment on why this was closed? (Side note: My PR #68 did *not* fix this issue - that was a separate issue where the generateKeyOffline parameter was not being passed through the extension method, but this issue still occurs if you use generateKeyOffline=true with WithAuth())

**Comment by bezysoftware** [comment]
Oops, I didn't read the whole thing and assumed they were related.

Anyway, WithAuth shouldn't be used for auth, it's internal only. Use FirebaseOptions to pass in the auth token. See https://github.com/step-up-labs/firebase-database-dotnet/blob/master/README.md

**Comment by briandunnington** [comment]
If WithAuth is internal only, it probably should not be exposed a a public member in QueryFactoryExtensions (https://github.com/step-up-labs/firebase-database-dotnet/blob/f4be3b7e34ae327653a9b4a8540db5b18c78b938/src/Firebase/Query/QueryFactoryExtensions.cs).

That said, it is convenient to be able to call WithAuth on individual calls. If I use the FirebaseOptions, I have to set the token factory function for all calls, so in order to do logic to decide to pass the token or not on individual calls, I have to track one more piece of state.
