### ISSUE TITLE
how to add AsObservable for node with 'variable' parent key

### ISSUE THREAD

**Issue by ywlau** [step-up-labs/firebase-database-dotnet#70]
```
Public void Init() {

   var child = firebase.Child("/units/{unitID}/members");

   var observable = child.AsObservable< MemberProfile >();

   var subscription = observable
     .Where(f => !string.IsNullOrEmpty(f.Key)) 
     .Subscribe(f => processMemberProfile(f.Object));
}

Private void processMemberProfile(MemberProfile profile) {
   // Perform task
}
```

Tried the above code with no success; The processMemberProfile() will not be called.

However, if {unitID} is replaced with one of the actual unit id then processMemberProfile() will be called as expected.

Please help. Thanks.

**Comment by bezysoftware** [comment]
That's not possible. You need to observe entire `units/` node to get all members

**Comment by ywlau** [comment]
Thanks for fast reply; anyway to add this feature ?

**Comment by bezysoftware** [comment]
No, the REST api this library uses doesn't enable that, see https://firebase.google.com/docs/reference/rest/database/
