### ISSUE TITLE
IObservable implementation

### ISSUE THREAD

**Issue by roberzyx** [step-up-labs/firebase-database-dotnet#72]
Hi Tomas,

My name is Roberto and I'm developing a Windows app using Firebase.

First of all, thanks for taking the time to build this library, it's been very useful to me. I hope you can help me implementing the IObservable in some kind of lists I have in my database. My Firebase DB is the following:

![image](https://cloud.githubusercontent.com/assets/28893010/26350284/ee18add4-3fb2-11e7-9cc0-ca9c6ea2cce0.png)

Sorry that it is in Spanish. I'll try to explain you the structure. What I want to do is listen for changes in any of the children in "productos" (products), but I don't know how to map the objects with my Producto class in my project. My code is something like this:

![image](https://cloud.githubusercontent.com/assets/28893010/26350081/399ea480-3fb2-11e7-832a-45283dbacf51.png)

I don't know exactly how to map the product children with my class that has the same properties as the product items of the DB. 

I would appreciate it a lot if you could help me with this. Again, thanks for your work, keep it up!

**Comment by yohaas** [comment]
Define your Producto class like this: 
```
   [DataContract]
    public class Producto
    {
        [DataMember(Name = "descripcion")]
        public string Descripcion{ get; set; }

        [DataMember(Name = "imagen")]
        public string Imagen{ get; set; }

        [DataMember(Name = "nombre")]
        public string Nombre{ get; set; }

        [DataMember(Name = "percio")]
        public doublePercio{ get; set; }
    }
```

The   `[DataMember(Name = "xxxx")]` allows you to use a different name for the class member than the name in Firebase - it's not required but makes things a little cleaner. 

Hope this helps.

**Comment by roberzyx** [comment]
Thanks for replying so quick. I've tried but nothing is happening. I guess my program should be showing the "pedidos" children, but nothing is happening. Is the main program code right?

![image](https://cloud.githubusercontent.com/assets/28893010/26358603/501b0ff2-3fd3-11e7-8680-3e002f815065.png)

**Comment by yohaas** [comment]
Make sure there is a "/" in the path (either where you define the client, or in the Child()". I can't tell if you have one because it's blurred out. 
For example: `Child(/"productos");`

**Comment by bezysoftware** [comment]
There is no need for the slash. I assume the issue is that the productos items are in an array instead of key-value pairs. Top-level arrays weren't support until very recently ( #62 ) and a nuget package hasn't been built yet. I plan on releasing one later this week, in the meantime you can try building from sources to verify latest code works for you

**Comment by roberzyx** [comment]
Ok, I think that might be the problem @bezysoftware . Is my Producto class right (with DataContract and DataMeber), or should I do it with JsonProperty as you do it the samples?

And please, let me know when you release the package so I'll be happy to test it. Thanks!

**Comment by bezysoftware** [comment]
The deserialization is done by json.net so you can use both. JsonProperty just offers more options
