### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by pallavbohara** [step-up-labs/firebase-database-dotnet#75]
I am integrating this library in Xamarin.Forms.
 var client = new FirebaseClient(
           "https://xxxxxxxxx-bdded.firebaseio.com/",
           new FirebaseOptions
           {
                OfflineDatabaseFactory = (t, s) => new OfflineDatabase(t, s),
               //AuthTokenAsyncFactory = () => Task.FromResult("<YOUR AUTH IF NEEDED>")
           });
 var messagesDb = client.Child("FlightPlans").AsRealtimeDatabase<WingMan.Models.FlightPlansModel>();

Getting this error on above line--
`System.NullReferenceException: Object reference not set to an instance of an object.
05-29 08:20:59.602 I/MonoDroid( 3220):   at Lex.Db.DbInstance.Initialize () [0x000a9] in <ea66c9ff13824a469a147846b99908c9>:0 
05-29 08:20:59.602 I/MonoDroid( 3220):   at Firebase.Database.Offline.OfflineDatabase..ctor (System.Type itemType, System.String filenameModifier) [0x00086] in <3737787f042f496f9cfc4ccb6ad11b87>:0 
05-29 08:20:59.602 I/MonoDroid( 3220):   at WingMan.Views.Test+<>c.<Storage>b__6_0 (System.Type t, System.String s) [0x00000] in <1656384416104e28bf1eaad25d02d4ad>:0 
05-29 08:20:59.602 I/MonoDroid( 3220):   at Firebase.Database.Offline.RealtimeDatabase`1[T]..ctor (Firebase.Database.Query.ChildQuery childQuery, System.String elementRoot, System.Func`3[T1,T2,TResult] offlineDatabaseFactory, System.String filenameModifier, System.Boolean streamChanges, Firebase.Database.Offline.InitialPullStrategy initialPullStrategy, System.Boolean pushChanges) [0x0002c] in <b98872d7859f4da0991da50887d63843>:0 
05-29 08:20:59.602 I/MonoDroid( 3220):   at Firebase.Database.Query.ChildQuery.AsRealtimeDatabase[T] (System.String filenameModifier, System.String elementRoot, System.Boolean streamChanges, Firebase.Database.Offline.InitialPullStrategy initialPullStrategy, System.Boolean pushChanges) [0x00012] in <b98872d7859f4da0991da50887d63843>:0 
05-29 08:20:59.602 I/MonoDroid( 3220):   at WingMan.Views.Test+<Storage>d__6.MoveNext () [0x00054] in <1656384416104e28bf1eaad25d02d4ad>:0 `

I only added this NuGet in portable(not in android & ios)
Thanks in advance!

**Comment by bezysoftware** [comment]
You need to add the the platform nuget in your droid & ios projects. Lex.DB uses dummy implenetation in PCLs to allow compilation, but this would fail during runtime
