### ISSUE TITLE
Custom token Authentication does not work 

### ISSUE THREAD

**Issue by oreporan** [step-up-labs/firebase-database-dotnet#78]
## Issue
We are using the library with a custom token generated on our own Authorization Server. In the Firebase-JS library this works using a method `signInWithCustomToken()` which goes to Firebase with the custom token and returns a firebase id token which is then used to authorize access to Firebase.
In the REST Api this needs to be done this way - 
https://firebase.google.com/docs/reference/rest/auth/#section-verify-custom-token

The Dot Net client accepts a custom token, but we need to make the call to verify that token ourselves and then give the Firebase Client the ID token for the client to actually connect to Firebase

## Suggestion
Make the Firebase client accept a custom token, and then internally make the call to have that token verified.

**Comment by TFAstudio** [comment]
Using the Firebase-Authentication-Dotnet package, they have already provided integration with a Custom Token
https://github.com/step-up-labs/firebase-authentication-dotnet

Just use the `SignInWithCustomTokenAsync()` method.

**Comment by oreporan** [comment]
Thanks! Looked at that library but it didn't mention support for CustomToken login
