### ISSUE TITLE
Adding the use of Firebase Admin SDK

### ISSUE THREAD

**Issue by PatCantSeeSharp** [step-up-labs/firebase-database-dotnet#80]
Since the use of app-secrets is not longer really recommeded it would be great if firebase-database-dotnet library also uses the generate .json file for authentication against firebase.

All the details can be found there: [https://firebase.google.com/docs/admin/setup](url)

**Comment by bezysoftware** [comment]
If you can figure out how to do it within the firebase-authentication-dotnet library, you can send a pull request there. https://github.com/step-up-labs/firebase-authentication-dotnet

**Comment by AndreasSchmid1** [comment]
why is this issue closed?

**Comment by bezysoftware** [comment]
Because it's in wrong repo. Admin setup is about Auth, not database

**Comment by AndreasSchmid1** [comment]
Thank makes sense. thx bezysoftware. i guess the corresponding issue is this one https://github.com/step-up-labs/firebase-authentication-dotnet/issues/38
