### ISSUE TITLE
Transaction Support

### ISSUE THREAD

**Issue by clarkezone** [step-up-labs/firebase-database-dotnet#82]
I'm planning on using this on Android and need support in this library to be able to build a cross platform solution.

**Comment by bezysoftware** [comment]
I don't think the REST api has any support for transactions. It only supports multi-path updates, which should be atomic. 
I might get to the multi-path updates in the future, but no immediate plans

**Comment by angularsen** [comment]
It does now, using ETag:
https://firebase.google.com/docs/database/rest/save-data#section-conditional-requests

**Comment by angularsen** [comment]
If `X-Firebase-ETag: true` header is passed for all requests so ETags are included in response and stored with cached entries, then I suppose the Put/Post methods can handle the retry logic automatically?
