### ISSUE TITLE
Can't reach nodes that are two nodes deeper than root node

### ISSUE THREAD

**Issue by Scarass93** [step-up-labs/firebase-database-dotnet#84]
For me this doesn't work:

`var firebase = new FirebaseClient("https://dinosaur-facts.firebaseio.com/");
firebase.Child("dinosaurs").Child("t-rex").PutAsync(new Dinosaur())`

Because firebase.Child returns ChildQuery object which doesn't have Child method.

If this really doesn't work, is there another way to get the deeper node?

Question on StackOverflow:
https://stackoverflow.com/questions/44990024/cant-reach-deeper-nodes-in-firebasedatabase-net

I'm using version 3.0.0 installed via NuGet.

**Comment by bezysoftware** [comment]
You just need to bring in the relevant namespaces:
```
using Firebase.Database;
using Firebase.Database.Query;
```
