### ISSUE TITLE
JsonSerializationException is thrown when calling OnceAsync on a node with numeric child indexes

### ISSUE THREAD

**Issue by E4est** [step-up-labs/firebase-database-dotnet#85]
Our Firebase Database looks something like this

root
| - node1
|      | + [0]
|      | + [1]
|      | + [2]
| + node2

`var temp = await firebase.Child("node1").OnceAsync<MyType>();`
When calling OnceAsync on that node like shown above JsonSerializationException is thrown.

This seems to be cause by line 38 in HttpClientExtensions.cs,
`var dictionary = JsonConvert.DeserializeObject<Dictionary<string, T>>(responseData);`
because such a database structure needs a List<T> rather than a Dictionary<string, T>.

I was able to "fix" this by crippling the method like this:

        public static async Task<IReadOnlyCollection<FirebaseObject<T>>> GetObjectCollectionAsync<T>(this HttpClient client, string requestUri)
        {
            var responseData = string.Empty;
            var statusCode = HttpStatusCode.OK;

            try
            {
                var response = await client.GetAsync(requestUri).ConfigureAwait(false);
                statusCode = response.StatusCode;
                responseData = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

                response.EnsureSuccessStatusCode();

                try
                {
                    var dictionary = JsonConvert.DeserializeObject<Dictionary<string, T>>(responseData);

                    if (dictionary == null)
                    {
                        return new FirebaseObject<T>[0];
                    }

                    return dictionary.Select(item => new FirebaseObject<T>(item.Key, item.Value)).ToList();
                }
                catch (JsonSerializationException)
                {
                    var list = JsonConvert.DeserializeObject<List<T>>(responseData);

                    if (list == null)
                    {
                        return new FirebaseObject<T>[0];
                    }

                    return list.Select(item => new FirebaseObject<T>("", item)).ToList();
                }
            }
            catch (Exception ex)
            {
                throw new FirebaseException(requestUri, string.Empty, responseData, statusCode, ex);
            }
        }

I am sure you could find a more elegant solution to this.
It also looks like you already did when I'm looking at the method in line 59 now...

**Comment by bezysoftware** [comment]
Instead of `OnceAsync<T>` you can try `OnceSingleAsync<List<T>>`, that could do the trick. Having numeric keys shifts the db structure to array instead of maps, which this lib doesn't support very well.

**Comment by E4est** [comment]
I like the result of this workaround more than that from my suggestion.
Maybe JsonSerializationException should still be caught and another Exception thrown to point out what went wrong, but FirebaseException doesn't sport custom messages. Something like "It looks like you used OnceAsync<T> on an array, try OnceSingleAsync<List<T>> instead." Could be easily identified by an `if (responseData.StartsWith("["))`.

Otherwise this could also do the job:

        public static async Task<IReadOnlyCollection<FirebaseObject<T>>> GetObjectCollectionAsync<T>(this HttpClient client, string requestUri)
        {
            var responseData = string.Empty;
            var statusCode = HttpStatusCode.OK;

            try
            {
                var response = await client.GetAsync(requestUri).ConfigureAwait(false);
                statusCode = response.StatusCode;
                responseData = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

                response.EnsureSuccessStatusCode();

                if (responseData.StartsWith("["))
                {
                    var list = JsonConvert.DeserializeObject<List<T>>(responseData);

                    if (list == null)
                    {
                        return new FirebaseObject<T>[0];
                    }

                    return list.Select(item => new FirebaseObject<T>("", item)).ToList();
                }
                else
                {
                    var dictionary = JsonConvert.DeserializeObject<Dictionary<string, T>>(responseData);

                    if (dictionary == null)
                    {
                        return new FirebaseObject<T>[0];
                    }

                    return dictionary.Select(item => new FirebaseObject<T>(item.Key, item.Value)).ToList();
                }
            }
            catch (Exception ex)
            {
                throw new FirebaseException(requestUri, string.Empty, responseData, statusCode, ex);
            }
        }

This just misses a valid key for `FirebaseObject`. Possibly `list.IndexOf(item)` could do it, but I'm not sure how it would handle possible duplicates. Another less elegant method would be to loop through the list object with a counter and add them to a returned List object or if you prefer to keep it a Dictionary, then add the counted index as key.

As I said, I like the `OnceSingleAsync` solution more than mine, I just wanted to share my idea, so it is saved somewhere and maybe someone finds a better solution based on this.
Have a nice day and keep up the good work!
