### ISSUE TITLE
How to handle Firebase.Database.FirebaseException raised by Firebase.Database.Streaming.FirebaseSubscription`1.<ReceiveThread>d__14.MoveNext()

### ISSUE THREAD

**Issue by ywlau** [step-up-labs/firebase-database-dotnet#87]
subscription codes:

private void init() 
{
	try
	{
		var ref= firebase.Child("Infos/updates");
		var observable = ref.AsObservable<InfoUpdate>();
		subscription = observable
			.Where(f => !string.IsNullOrEmpty(f.Key)) 
			.Subscribe(f => processInfoUpdate(f.Object));
	}
	catch (Exception ex)
	{
	}
}

private void processInfoUpdate(InfoUpdate update)
{
	try
	{
            //process update
	}
	catch (Exception ex)
	{
	}
}

The code was running ok initially; after sometime, the following exception is thrown.
Tried putting the relevant codes in try catch block, but doesn't help.
What's the best way to handle this exception ?

Firebase.Database.FirebaseException: Exception occured while processing the request.
Url: https://myproject.firebaseio.com/Infos/updates/.json?auth=verylongauthstring
Request Data: 
Response:  ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Firebase.Database.Streaming.FirebaseSubscription`1.<ReceiveThread>d__14.MoveNext()
   --- End of inner exception stack trace ---
   at System.Reactive.PlatformServices.DefaultExceptionServices.Rethrow(Exception exception)
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Where`1._.OnError(Exception error)
   at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception)
   at System.Reactive.ObserverBase`1.OnError(Exception error)
   at Firebase.Database.Streaming.FirebaseSubscription`1.<ReceiveThread>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by bezysoftware** [comment]
`Response status code does not indicate success: 401 (Unauthorized).`

This means the auth token is not valid

**Comment by ywlau** [comment]
how should i handle it when the auth token is expired (the code was running fine initially) ?

btw, AuthLink_FirebaseAuthRefreshed event is not raised.


Thanks

**Comment by bezysoftware** [comment]
There is no such event `AuthLink_FirebaseAuthRefreshed`, I don't know how it should be raised. 

Refreshing token is described here: https://github.com/step-up-labs/firebase-authentication-dotnet/pull/14#issue-198242796

**Comment by ywlau** [comment]
incorporated the refreshing token strategy and ran the app. twice; with subscription and without.

auth.FirebaseAuthRefreshed is not called in both runs and Firebase.Database.FirebaseException is thrown only if subscription is included.


I'm using FirebaseAuthentication.net v3.0.5 and FirebaseDatabase.net v3.0.0




```
private void init()
{
	authProvider = new FirebaseAuthProvider(new FirebaseConfig(FirebaseAppKey));
	auth = Task.Run(() => authProvider.SignInWithEmailAndPasswordAsync("myemail", "mypassword")).Result;
	auth.FirebaseAuthRefreshed += AuthLink_FirebaseAuthRefreshed;

        ......
}


private void AuthLink_FirebaseAuthRefreshed(object sender, FirebaseAuthEventArgs e)
{
	auth = Task.Run(() => auth.GetFreshAuthAsync()).Result;

	firebase = new FirebaseClient(
	FirebaseAppUri,
	new FirebaseOptions
	{
		AuthTokenAsyncFactory = () => Task.FromResult(auth.FirebaseToken)
	});
}
```

**Comment by ywlau** [comment]
from Firebase.Auth source code; it seems we need to call the following method to trigger the auth.FirebaseAuthRefreshed event, right ?

`var freshAuth = auth.GetFreshAuthAsync().Result;`

if so, what's the best practice; call regularly in timer ?

Thank You.

**Comment by bezysoftware** [comment]
Use it in FirebaseOptions:

```
new FirebaseOptions
	{
		AuthTokenAsyncFactory = async () => (await auth.GetFreshAuthAsync()).FirebaseToken
	});
```

FirebaseAuthRefreshed event is raised to give you a chance to save the token to storage & load it upon application restart (e.g. user logs in with facebook and the token is kept so he doesn't need to login again after app restart)

**Comment by ywlau** [comment]
just some feedback; in addition of refreshing token strategy, i also added err handling in subscription to handle all other potential exception gracefully.

```
private void init()
{
try
{
   var ref= firebase.Child("Infos/updates");
   var observable = ref.AsObservable();
   subscription = observable
      .Where(f => !string.IsNullOrEmpty(f.Key))
      .Subscribe(f => processInfoUpdate(f.Object),
         ex =>processInfoErr(),
         () => processInfoComplete();
}
catch (Exception ex)
{
}
}
```

thank you again for the good work

btw, where can i find the latest source code of FirebaseDatabase.net project (Nuget v3.0.5 and Github v.2.0.0) ?

**Comment by bezysoftware** [comment]
What do you mean where you can find sources for the nuget? They are all here on github: https://github.com/step-up-labs/firebase-database-dotnet
