### ISSUE TITLE
No Way To Set Own Keys

### ISSUE THREAD

**Issue by techfinity** [step-up-labs/firebase-database-dotnet#89]
I Would like to set my own keys instead of having the generated one pop up . Is there a way to do that with this library. In other libraries for other languages they have the Set function but this library doesn't seem to offer it. Please any help is greatly appreciated

**Comment by bezysoftware** [comment]
You can Put(...)

**Comment by alexhuiculescu** [comment]
I found a good way to do that:

**1.Use Patch:**
Suppose you want to Push an 'UserModel' object with your own key. Using patch and formatting a little the string you want to send, you cand accomplish that: 
`FirebaseClient.Child("test/patch_test"). PatchAsync("\"Kdhekasdjk223jsadkj\":"+JsonConvert.SerializeObject(userModel)+"}");`

The expression above is the JSON with the desired key, and it's value is the converted object
