### ISSUE TITLE
Serialize object with camelCase instead of PascalCase.

### ISSUE THREAD

**Issue by AbeBaehaki** [step-up-labs/firebase-database-dotnet#9]
It would be nice to be able to change the serializer setting to use camelCase instead of PascalCase for storing object to Firebase. Maybe as a new option in `FirebaseOptions`?

PascalCase
```json
{
  "FirstName": "John",
  "LastName": "Doe"
}
```

camelCase
```json
{
  "firstName": "John",
  "lastName": "Doe"
}
```

If you need a hand, I will be happy to help. Cheers!

**Comment by bezysoftware** [comment]
Under the hood the serialization is done using Json.net - meaning you can decorate your properties with [JsonProperty] attributes and specify custom names.
But I agree it is annoying having to set the attribute everywhere, I will look into adding it into the firebase options

**Comment by bezysoftware** [comment]
016ce53dafa74f2cf2ec866f555683472e24e9e5 should resolve this. You can now specify custom JsonSerializationSettings in the FirebaseOptions:

```
var options = new FirebaseOptions 
{
  JsonSerializerSettings = new JsonSerializerSettings 
  { 
     ContractResolver = new CamelCasePropertyNamesContractResolver() 
  } 
}
```
