### ISSUE TITLE
Problems with firebase database platform.net

### ISSUE THREAD

**Issue by jcarlos79t** [step-up-labs/firebase-database-dotnet#91]
Can not Add to a Class Library Project. vs2017 community

**Comment by jcarlos79t** [comment]
Why?

**Comment by bezysoftware** [comment]
I can't tell you if you don't tell me what the error is

**Comment by bezysoftware** [comment]
What is the error? What type of class library is it? 

Platform package is to designed to be installed to your *platform*-specific project - UWP / .NET 4.5 / asp.net etc, not class library

**Comment by felipeoliveirar** [comment]
hi. I had the same problem. There is any workarround? I am using Xamarin.Forms. It is able to use this Packge in this case? if yes. Some sample?

**Comment by felipeoliveirar** [comment]
I got to do that work.

**Comment by jcarlos79t** [comment]
Would be good, that could be used in class libraries. Could it be in the future ??  :9

**Comment by bezysoftware** [comment]
Platform package is gone in latest alpha, LexDB was replaced by LiteDB
