### ISSUE TITLE
Does this supports FCM messages?

### ISSUE THREAD

**Issue by chandrakantnitt** [step-up-labs/firebase-database-dotnet#93]
Does this version supports FCM messages?  https://firebase.google.com/docs/cloud-messaging/concept-options

**Comment by bezysoftware** [comment]
No, this library only supports firebase database

**Comment by chandrakantnitt** [comment]
Thanks @bezysoftware. Do you know any .net lib which does support FCM ? I am currently exploring https://github.com/tiagomtotti/firebaseNet

**Comment by jaybowman** [comment]
If you want to send FCM notifications from C# code all you need to do is use a HTTPClient of your choice. I use RestSharp, very easy to use. Check firebase docs.
