### ISSUE TITLE
CPU spinning when streaming

### ISSUE THREAD

**Issue by IsaackRasmussen** [step-up-labs/firebase-database-dotnet#94]
I get this issue after running with streaming for about 12 hours where my process will start using all CPU on thread.

When I attach to process or break all with CPU profiling, it always points to this method
Firebase.Database.Streaming.FirebaseSubscription`1.<ReceiveThread>d__14.MoveNext()

I might be reading the callstack wrong, but it always seem centered around .ReadLine

When I got the source code attached, I got into this loop.
Is it possible that this loop can start spinning the cpu without any break?

This is from: FirebaseSubscription.cs

  using (var stream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false))
                    using (var reader = this.client.Options.SubscriptionStreamReaderFactory(stream))
                    {
                        while (true)
                        {
                            this.cancel.Token.ThrowIfCancellationRequested();

                            line = reader.ReadLine()?.Trim();

                            if (string.IsNullOrWhiteSpace(line))
                            {
                                continue;
                            }

                            var tuple = line.Split(new[] { ':' }, 2, StringSplitOptions.RemoveEmptyEntries).Select(s => s.Trim()).ToArray();
                            
                            switch (tuple[0].ToLower())
                            {
                                case "event":
                                    serverEvent = this.ParseServerEvent(serverEvent, tuple[1]);
                                    break;
                                case "data":
                                    this.ProcessServerData(url, serverEvent, tuple[1]);
                                    break;
                            }

                            if (serverEvent == FirebaseServerEventType.AuthRevoked)
                            {
                                // auth token no longer valid, reconnect
                                break;
                            }
                        }
                    }

Also, how often do these keep-alive messages get sent out? It seems like every few seconds.

I'm running Debug builds with Visual Studio 2017 15.3 and .NET 4.6.1
I've noticed the other thread with re-authenticating... but it doesn't seem to be the case, also I've added the re-auth code that was suggested.

**Comment by TFAstudio** [comment]
Why do you have a loop to read the subscription?  I can see the loop without too much to make it pause would certainly cause some issues...  It is far simpler than this - at least in my experience.

If you use the `AsObservable<T>()` and subscribe it to a function, the function receives the type `T` as a `FirebaseEvent<T>` without needing to set up a thread.

For example, if you have a FirebaseClient _client set up, the following code:

```
_client
    .Child("cities")
    .AsObservable<City>()
    .Subscribe(x => CacheCities(x));
```

This code will set up a watcher in` CacheCities(FirebaseEvent<City> cityEvent)` so you can do something with the city that was inserted or modified or deleted (checked by the `FirebaseEventType`) in the `FirebaseEvent`, so you do not need a thread.

The code to receive the data would look something like:

```
    private void CacheCities(FirebaseEvent<City> fbCity)
    {
        if (fbCity.EventType == FirebaseEventType.InsertOrUpdate)
        {
            _list[x.Key] = fbCity.Object;
        }
        else
            if (_list.ContainsKey(x.Key)) _list.Remove(x.Key);
    }
```

You may have to do some tricky stuff with the AuthToken and logging in to check to see if there is any timeouts, but really, I have not had any issues.  This function will launch each time there is a new event from Firebase - whether it is from your application or another source.

Hope this helps

**Comment by IsaackRasmussen** [comment]
Hi,

Its not my code but from the Firebase subscription/streaming code.
When I try to figure out where the CPU usage is coming from, its in that file my debugger points to and so far, that's the loop I've pinpointed.

Otherwise, I'm doing just as you suggest including the token refresh.

**Comment by IsaackRasmussen** [comment]
I managed to get a bit more data out of a case when it was spinning CPU cycles.

It was stuck here and the event was "CANCEL". I'm not sure it makes sense to me according to the docs,
https://www.firebase.com/docs/rest/guide/retrieving-data.html#section-rest-streaming
According to the code, it should cause a Unauthorized exception but I don't see it anywhere.. and this also happened within 1minute of running.

Firebase.Database.FirebaseException: Exception occured while processing the request.
Url: https://db.firebaseio.com/messages/emails/pending/.json?orderBy="sendDateTime"&endAt="1503392326.31061"&auth=******
Request Data: 
Response:  ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Firebase.Database.Query.FirebaseQuery.<OnceSingleAsync>d__7`1.MoveNext() in C:\Projects\firebase-database-dotnet-master\src\Firebase\Query\FirebaseQuery.cs:line 88
   --- End of inner exception stack trace ---
   at Firebase.Database.Query.FirebaseQuery.<OnceSingleAsync>d__7`1.MoveNext() in C:\Projects\firebase-database-dotnet-master\src\Firebase\Query\FirebaseQuery.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at oevent.busi.NotificationBusi.<GetPendingEmailNotifications>d__10.MoveNext() in

**Comment by grant1842** [comment]
I'm also having an issue with CPU spinning out.  For me, every test seems to take a couple hours but sooner  or later it spins.  Any help would be much appreciated.  Thank you very much.

**Comment by guiltm** [comment]
did you get any solution?

**Comment by guiltm** [comment]
1 week and my code are working without that issue.. 
I will send a PR.

**Comment by guiltm** [comment]
3 month without that problem. I sent a PR. 
https://github.com/step-up-labs/firebase-database-dotnet/pull/254
