### ISSUE TITLE
How to query  "PropertyName" == "value"

### ISSUE THREAD

**Issue by passa1248** [step-up-labs/firebase-database-dotnet#95]
Hi all!
I need to get json from fireDatabase with query like PropertyName" == "value" is it possible?
For example

this is json stored in firedatabase:
`"Matches":{
  "-Ks9mehmDGk-PsBsOv8e" : {

      "MatchName" : {
        "AwayTeam" : "Manchester City",
        "HomeTeam" : "Bournemouth"
      },
     
    "MatchDate" : "2017-08-26T12:30:00"
  },
  
  "-Ks9mf-8iC27M_FUOvkN" : {

      "MatchName" : {
        "AwayTeam" : "Leicester",
        "HomeTeam" : "Manchester United
      },  
    "MatchDate" : "2017-08-26T17:30:00"
  }
}`

I need to get json match where MatchDate == 2017-08-26T17:30:00.

is it possible?
Thanks in advance

**Comment by jaybowman** [comment]
Yes, you need to have an index on "MatchDate" in your firebase rules.
Then something like this:  
      var firebaseObject = await _client.Child("parentCollectionName")
                                       .OrderBy("MatchDate")
                                       .EqualTo("2017-08-26T17:30:00")
                                       .OnceAsync<MatchObj>();

**Comment by jaybowman** [comment]
a little more explination:

var firebaseObject = await _client.Child("parentCollectionName")
.OrderBy("MatchDate")
.EqualTo("2017-08-26T17:30:00")
.OnceAsync<MyMatchObj>();
The firebaseObject will be a collection and you can do Linq statements with it.

**Comment by passa1248** [comment]
OK nice, thank you so much!
